//! VERIFIER adversarial tests for item `w1-num-pcode-semantics` (round 1).
//!
//! Written by the independent verifier against the C++ in scope
//! (`decompiler/cpp/opcodes.cc/.hh`, `pcoderaw.cc/.hh`, `opbehavior.cc/.hh`),
//! targeting the surfaces the golden gate does NOT pin:
//!
//! 1. `recoverInputUnary`/`recoverInputBinary` (no golden rows exist) —
//!    replayed against a freshly captured C++ oracle run
//!    (`tests/data/verify_w1_pcode_oracle.out`, generated by
//!    `tests/data/verify_w1_pcode_oracle_harness.cc` linked against the
//!    decomp_dbg objects at C++ tree rev 87016be).  This sweeps the
//!    x86-masked / negative shift-count idioms (`8*sizeout-sa` hitting 64,
//!    `sizein*8-sa-1` going negative when sizein < sizeout) and the
//!    EvaluationError-vs-LowlevelError classification.
//! 2. `get_opcode` lookups including the UB-1 surface, and `get_booleanflip`
//!    over the full enum (same oracle file).  NOTE: the C++ oracle
//!    **segfaults** on `get_opcode("ZPULL")` / `get_opcode("SPULL")` (the
//!    binary search probes the out-of-bounds sorted slot 74), so those rows
//!    cannot exist in the oracle file — the Rust fix is asserted directly.
//! 3. `VarnodeData` comparator totality / Ord-Eq consistency and the
//!    `contains` size-0 `uint4` wrap (hand-derived from the C++ integer
//!    semantics: `size-1` wraps in u32, the add wraps in u64).
//! 4. The packed/XML opcode marshaling protocol pinned by LOSS-013's
//!    restoration criteria: packed `(int4)` truncation + `CPUI_MAX` range
//!    check, XML mnemonic round-trip for every operation, and the
//!    "Bad encoded OpCode" error paths.

use std::rc::Rc;

use kuna_base::error::KunaError;
use kuna_base::marshal::{
    Decoder, Encoder, IdRegistry, PackedDecode, PackedEncode, XmlDecode, XmlEncode,
};
use kuna_base::space::{addrspace_flags, spacetype, AddrSpace, AddrSpaceManager, ConstantSpace};
use kuna_num::opbehavior::{
    OpBehavior, OpBehaviorCopy, OpBehaviorInt2Comp, OpBehaviorIntAdd, OpBehaviorIntLeft,
    OpBehaviorIntNegate, OpBehaviorIntRight, OpBehaviorIntSext, OpBehaviorIntSright,
    OpBehaviorIntSub, OpBehaviorIntZext,
};
use kuna_num::opcodes::{
    get_booleanflip, get_opcode, get_opname, OpCode, OpcodeDecoder, OpcodeEncoder,
};
use kuna_num::pcoderaw::{PcodeOpRaw, VarnodeData, ATTRIB_CODE};

const ORACLE: &str = include_str!("data/verify_w1_pcode_oracle.out");

fn parse_hex(s: &str) -> u64 {
    u64::from_str_radix(s.trim_start_matches("0x"), 16).unwrap()
}

/// The C++ harness streams `"0x" << recoverInput...(...)`, so when the call
/// throws, the cell reads `0xEVALERR`/`0xLOWERR` (the prefix was already
/// emitted).  Normalize that prefix away.
fn oracle_cell(s: &str) -> &str {
    match s {
        "0xEVALERR" => "EVALERR",
        "0xLOWERR" => "LOWERR",
        other => other,
    }
}

/// Map a Rust recover result onto the oracle cell text.
fn recover_cell(res: Result<u64, KunaError>) -> String {
    match res {
        Ok(v) => format!("0x{v:x}"),
        Err(KunaError::Evaluation { .. }) => "EVALERR".to_string(),
        Err(KunaError::Lowlevel { .. }) => "LOWERR".to_string(),
        Err(other) => format!("UNEXPECTED({other:?})"),
    }
}

fn recover_binary(name: &str, slot: i32, sizeout: i32, out: u64, sizein: i32, in_: u64) -> String {
    let res = match name {
        "INT_ADD" => OpBehaviorIntAdd.recover_input_binary(slot, sizeout, out, sizein, in_),
        "INT_SUB" => OpBehaviorIntSub.recover_input_binary(slot, sizeout, out, sizein, in_),
        "INT_LEFT" => OpBehaviorIntLeft.recover_input_binary(slot, sizeout, out, sizein, in_),
        "INT_RIGHT" => OpBehaviorIntRight.recover_input_binary(slot, sizeout, out, sizein, in_),
        "INT_SRIGHT" => OpBehaviorIntSright.recover_input_binary(slot, sizeout, out, sizein, in_),
        other => panic!("unknown binary op {other}"),
    };
    recover_cell(res)
}

fn recover_unary(name: &str, sizeout: i32, out: u64, sizein: i32) -> String {
    let res = match name {
        "COPY" => OpBehaviorCopy.recover_input_unary(sizeout, out, sizein),
        "INT_ZEXT" => OpBehaviorIntZext.recover_input_unary(sizeout, out, sizein),
        "INT_SEXT" => OpBehaviorIntSext.recover_input_unary(sizeout, out, sizein),
        "INT_2COMP" => OpBehaviorInt2Comp.recover_input_unary(sizeout, out, sizein),
        "INT_NEGATE" => OpBehaviorIntNegate.recover_input_unary(sizeout, out, sizein),
        other => panic!("unknown unary op {other}"),
    };
    recover_cell(res)
}

/// 1. Replay every C++ oracle recover row (5187 cells: full
///    size-out x size-in x output x shift matrix incl. counts 64 and
///    u64::MAX, plus the slot != 0 fallthroughs).
#[test]
fn verify_recover_paths_match_cpp_oracle() {
    let mut rows = 0usize;
    for (lineno, line) in ORACLE.lines().enumerate() {
        let f: Vec<&str> = line.split(',').collect();
        match f[0] {
            "recb" => {
                let (name, slot, sizeout, out, sizein, in_) = (
                    f[1],
                    f[2].parse::<i32>().unwrap(),
                    f[3].parse::<i32>().unwrap(),
                    parse_hex(f[4]),
                    f[5].parse::<i32>().unwrap(),
                    parse_hex(f[6]),
                );
                let got = recover_binary(name, slot, sizeout, out, sizein, in_);
                assert_eq!(
                    got,
                    oracle_cell(f[7]),
                    "oracle line {}: recoverInputBinary({name},slot={slot},sizeout={sizeout},out={out:#x},sizein={sizein},in={in_:#x})",
                    lineno + 1
                );
                rows += 1;
            }
            "recu" => {
                let (name, sizeout, out, sizein) = (
                    f[1],
                    f[2].parse::<i32>().unwrap(),
                    parse_hex(f[3]),
                    f[4].parse::<i32>().unwrap(),
                );
                let got = recover_unary(name, sizeout, out, sizein);
                assert_eq!(
                    got,
                    oracle_cell(f[5]),
                    "oracle line {}: recoverInputUnary({name},sizeout={sizeout},out={out:#x},sizein={sizein})",
                    lineno + 1
                );
                rows += 1;
            }
            _ => {}
        }
    }
    assert_eq!(rows, 5187, "oracle recover row count");
}

/// 2a. Replay the C++ `get_opcode` lookups.  The two cells where the C++
/// answer is an enum value Rust deliberately cannot represent are the
/// documented UB-1 / invalid-value surface and are asserted as such.
#[test]
fn verify_get_opcode_matches_cpp_oracle() {
    let mut rows = 0usize;
    for line in ORACLE.lines() {
        let f: Vec<&str> = line.split(',').collect();
        if f[0] != "getop" {
            continue;
        }
        // harness row: getop,<name>,<int result>  (name may be empty)
        let name = f[1];
        let cpp: i32 = f[2].parse().unwrap();
        let rust = get_opcode(name);
        match (name, cpp) {
            // C++ materializes the nameless in-range value (OpCode)45;
            // OpCode::from_i32 maps it to None (opcodes.rs docs).
            ("UNUSED1", 45) => assert_eq!(rust, None),
            // UB-1: the stale C++ table still resolves "EXTRACT" to 71; the
            // regenerated Rust table does not (CPUI_ZPULL's canonical name
            // is "ZPULL").
            ("EXTRACT", 71) => assert_eq!(rust, None),
            (_, 0) => assert_eq!(rust, None, "lookup of {name:?}"),
            (_, v) => assert_eq!(rust, OpCode::from_i32(v), "lookup of {name:?}"),
        }
        rows += 1;
    }
    assert_eq!(rows, 16, "oracle getop row count");
}

/// 2b. The UB-1 fix itself: the C++ oracle SEGFAULTS on these two lookups
/// (binary-search probe of the out-of-bounds sorted slot 74 — reproduced
/// while capturing the oracle file), so they are asserted directly against
/// the documented requirement in docs/rust-port/upstream-bugs.md.
#[test]
fn verify_ub1_lookups_resolve_instead_of_crashing() {
    assert_eq!(get_opcode("ZPULL"), Some(OpCode::CPUI_ZPULL));
    assert_eq!(get_opcode("SPULL"), Some(OpCode::CPUI_SPULL));
    // Names sorting above every table entry walk the same search path that
    // reads out of bounds in C++.
    assert_eq!(get_opcode("ZZZZZ"), None);
    assert_eq!(get_opname(OpCode::CPUI_ZPULL), "ZPULL");
    assert_eq!(get_opname(OpCode::CPUI_SPULL), "SPULL");
}

/// 2c. Replay the C++ `get_booleanflip` sweep over the whole enum.
#[test]
fn verify_booleanflip_matches_cpp_oracle() {
    let mut rows = 0usize;
    for line in ORACLE.lines() {
        let f: Vec<&str> = line.split(',').collect();
        if f[0] != "bflip" {
            continue;
        }
        let raw: i32 = f[1].parse().unwrap();
        let cpp_flip: i32 = f[2].parse().unwrap();
        let cpp_reorder: i32 = f[3].parse().unwrap();
        let opc = OpCode::from_i32(raw).unwrap();
        let mut reorder = false; // the C++ harness passes reorder=false in
        let flip = get_booleanflip(opc, &mut reorder);
        assert_eq!(flip as i32, cpp_flip, "flip of opcode {raw}");
        assert_eq!(i32::from(reorder), cpp_reorder, "reorder of opcode {raw}");
        rows += 1;
    }
    assert_eq!(rows, 73, "oracle bflip row count");
}

fn test_manager() -> AddrSpaceManager {
    let mut manager = AddrSpaceManager::new();
    manager.insert_space(Rc::new(ConstantSpace::new())).unwrap();
    let ram = AddrSpace::new(
        spacetype::IPTR_PROCESSOR,
        "ram",
        false,
        8,
        1,
        1,
        addrspace_flags::hasphysical,
        1,
        1,
    );
    manager.insert_space(Rc::new(ram)).unwrap();
    manager
}

fn vn(space: Rc<AddrSpace>, offset: u64, size: u32) -> VarnodeData {
    VarnodeData { space: Some(space), offset, size }
}

/// 3a. VarnodeData ordering: equal-key behavior, big-sizes-first inversion,
/// and Ord/Eq consistency (comparator-totality hunt item).  The C++
/// `operator<` is (space index, offset asc, size DESC); `operator==` is
/// identity on all three fields.
#[test]
fn verify_varnodedata_ord_total_and_consistent_with_eq() {
    let manager = test_manager();
    let r = Rc::clone(manager.get_space_by_name("ram").unwrap());
    let c = Rc::clone(manager.get_constant_space().unwrap());

    // BIG sizes first at equal (space, offset): strictly decreasing size.
    let mut v = [
        vn(Rc::clone(&r), 0x10, 1),
        vn(Rc::clone(&r), 0x10, 8),
        vn(Rc::clone(&r), 0x10, 4),
        vn(Rc::clone(&r), 0x10, 2),
    ];
    v.sort(); // stable sort, like std::sort's strict-weak requirement allows
    let sizes: Vec<u32> = v.iter().map(|x| x.size).collect();
    assert_eq!(sizes, vec![8, 4, 2, 1]);

    // Total-order laws over a mixed set (incl. u64::MAX offsets and size 0).
    let pool = [
        vn(Rc::clone(&c), 0, 0),
        vn(Rc::clone(&c), u64::MAX, 4),
        vn(Rc::clone(&r), 0, 4),
        vn(Rc::clone(&r), 0, 0),
        vn(Rc::clone(&r), u64::MAX, 8),
        vn(Rc::clone(&r), u64::MAX, 4),
        vn(Rc::clone(&r), 0x10, 4),
    ];
    for a in &pool {
        for b in &pool {
            // antisymmetry + Eq consistency
            let ord = a.cmp(b);
            assert_eq!(ord.reverse(), b.cmp(a));
            assert_eq!(ord == std::cmp::Ordering::Equal, a == b);
            for x in &pool {
                // transitivity spot-sweep
                if a.cmp(b) != std::cmp::Ordering::Greater
                    && b.cmp(x) != std::cmp::Ordering::Greater
                {
                    assert_ne!(a.cmp(x), std::cmp::Ordering::Greater);
                }
            }
        }
    }
}

/// 3b. `contains` size-0 wrap: C++ computes `offset + (uint4)(size-1)`, so
/// size 0 wraps to 0xffffffff (NOT u64::MAX) and the u64 add wraps mod 2^64.
/// Hand-derived oracle:
///   this=(ram,0,0)      -> end = 0 + 0xffffffff = 0xffffffff
///   op2 =(ram,0,4)      -> end = 3            -> contained
///   op2 =(ram,0x100000000,1) -> end > this end -> NOT contained
///   this=(ram,u64::MAX,2) -> end = u64::MAX + 1 wraps to 0
#[test]
fn verify_varnodedata_contains_wrap_semantics() {
    let manager = test_manager();
    let r = Rc::clone(manager.get_space_by_name("ram").unwrap());

    let zero_size = vn(Rc::clone(&r), 0, 0);
    assert!(zero_size.contains(&vn(Rc::clone(&r), 0, 4)));
    assert!(zero_size.contains(&vn(Rc::clone(&r), 0xffff_0000, 0x10000))); // end exactly 0xffffffff
    assert!(!zero_size.contains(&vn(Rc::clone(&r), 0x1_0000_0000, 1))); // starts past the wrapped end
    // size-0 op2: its end also wraps to op2.offset + 0xffffffff
    assert!(!zero_size.contains(&vn(Rc::clone(&r), 1, 0))); // 0xffffffff < 0x1_0000_0000

    // u64 end wrap: offset u64::MAX, size 2 -> end = u64::MAX+1 = 0
    let top = vn(Rc::clone(&r), u64::MAX, 2);
    assert!(!top.contains(&vn(Rc::clone(&r), u64::MAX, 1))); // 0 < u64::MAX: range check fails
    assert!(top.contains(&vn(Rc::clone(&r), u64::MAX, 2))); // equal wrapped ends
}

/// 4a. Packed opcode protocol: the C++ `(int4)readSignedInteger()`
/// truncation and the `val < 0 || val >= CPUI_MAX` range check
/// (LOSS-013 restoration criteria).
#[test]
fn verify_packed_opcode_truncation_and_range() {
    let manager = test_manager();

    // raw i64 -> what PackedDecode::readOpcode must yield
    let cases: [(i64, Option<OpCode>); 8] = [
        (74, Some(OpCode::CPUI_SPULL)),         // top valid value
        (75, None),                             // CPUI_MAX rejected
        (0, None),                              // (OpCode)0 in C++: error path either way
        (45, None),                             // nameless slot: C++ returns 45, Rust rejects (documented)
        (-1, None),                             // negative rejected
        (0x1_0000_0001, Some(OpCode::CPUI_COPY)), // (int4) truncation -> 1
        (0x1_0000_004B, None),                  // truncates to 75 -> rejected
        (i64::MIN, None),                       // truncates to 0 -> rejected
    ];
    for (raw, want) in cases {
        let mut stream: Vec<u8> = Vec::new();
        {
            let mut enc = PackedEncode::new(&mut stream);
            enc.open_element(&kuna_base::address::ELEM_ADDR);
            enc.write_signed_integer(&ATTRIB_CODE, raw);
            enc.close_element(&kuna_base::address::ELEM_ADDR);
        }
        let mut dec = PackedDecode::new(&manager);
        dec.ingest_stream(&stream).unwrap();
        dec.open_element().unwrap();
        let got = dec.read_opcode_id(&ATTRIB_CODE);
        match want {
            Some(op) => assert_eq!(got.unwrap(), op, "raw {raw:#x}"),
            None => match got {
                Err(KunaError::Decoder { explain }) => {
                    assert_eq!(explain, "Bad encoded OpCode", "raw {raw:#x}")
                }
                other => panic!("raw {raw:#x}: expected Bad encoded OpCode, got {other:?}"),
            },
        }
    }
    // 45 is the one packed cell where C++ (returning (OpCode)45) and the
    // port (rejecting) differ; everything else above matches the C++
    // readOpcode contract exactly.
}

/// 4b. XML opcode protocol: write_opcode/read_opcode round-trip for EVERY
/// real operation through PcodeOpRaw::decode's attribute path, byte-level:
/// the attribute must hold the (escape-free) mnemonic.
#[test]
fn verify_xml_opcode_roundtrip_all_ops() {
    let manager = test_manager();
    let registry = IdRegistry::with_base_ids();
    for raw in 1..OpCode::CPUI_MAX as i32 {
        let Some(op) = OpCode::from_i32(raw) else { continue };
        let mut buf: Vec<u8> = Vec::new();
        {
            let mut enc = XmlEncode::new(&mut buf);
            enc.open_element(&kuna_base::address::ELEM_ADDR);
            enc.write_opcode(&ATTRIB_CODE, op);
            enc.close_element(&kuna_base::address::ELEM_ADDR);
        }
        let text = String::from_utf8(buf.clone()).unwrap();
        assert!(
            text.contains(&format!("code=\"{}\"", get_opname(op))),
            "encoded text for {op:?}: {text}"
        );
        let mut dec = XmlDecode::new(&manager, &registry);
        dec.ingest_stream(&buf).unwrap();
        dec.open_element().unwrap();
        assert_eq!(dec.read_opcode_id(&ATTRIB_CODE).unwrap(), op);
    }
}

/// 4c. PcodeOpRaw::decode leaves caller state alone up to the failure point
/// (exception -> Result partial-state parity hunt item): a bad opcode fails
/// before outvar/invar are touched, exactly as the C++ throw from
/// readOpcode happens before any varnode decode.
#[test]
fn verify_decode_bad_opcode_preserves_outvar() {
    let manager = test_manager();
    let registry = IdRegistry::with_base_ids();
    let mut dec = XmlDecode::new(&manager, &registry);
    dec.ingest_stream(b"<op code=\"EXTRACT\"><void/></op>").unwrap();
    dec.open_element().unwrap();
    let mut invar: Vec<VarnodeData> = Vec::new();
    let sentinel = vn(Rc::clone(manager.get_space_by_name("ram").unwrap()), 0xabcd, 4);
    let mut outvar = Some(sentinel.clone());
    let res = PcodeOpRaw::decode(&mut dec, 0, &mut invar, &mut outvar);
    assert!(matches!(res, Err(KunaError::Decoder { .. })));
    // the C++ throw happens before *outvar is written; the port must too
    assert_eq!(outvar.as_ref().unwrap(), &sentinel);
    assert!(invar.is_empty());
}
