//! The kuna-native `.fid` fingerprint database — flat, fixed-record, full-hash
//! indexed.
//!
//! # What this is
//!
//! Deliberately **not** Ghidra's generic `db` packed-BTree format (the multi-GB
//! `.fidb`/`.fidbf` datasets are a separate Ghidra release artifact, not in the
//! source tree, not vendorable — see `docs/history/fid-design.md` §1). kuna ships the FID
//! *mechanism* and its **own** flat `.fid` format, generated by kuna from a static
//! library (`kuna fid build`) and vendored tiny.
//!
//! The format is nevertheless modeled **field-for-field** on Ghidra's FID
//! `FunctionsTable` + `StringsTable` (the per-record `fullHash`/`specificHash`/
//! `codeUnitSize`/`specificCodeUnitSize`/`flags` columns + an interned string
//! blob), so a future read-only `.fidbf` reader (deferred PR6) is a *serialization
//! swap behind the [`FidDb`] trait*, not a model change.
//!
//! # On-disk format (`docs/history/fid-design.md` §5.1)
//!
//! ```text
//! magic        "KFID"                         # 4 bytes
//! version      u32  (= FID_DB_VERSION = 1)     # bump on ANY hash/skipper change
//! lang_id      len-prefixed UTF-8              # SLEIGH language id (program must match)
//! cspec_id     len-prefixed UTF-8              # compiler-spec id
//! n_records    u32
//! records[n]:  full_hash:u64 | specific_hash:u64 | code_unit_size:i16 |
//!              specific_addl:u8 | flags:u8 | name_off:u32
//! string_blob  (interned, NUL-separated UTF-8)
//! ```
//!
//! All multi-byte integers are **little-endian**. A length prefix is a `u32`. A
//! `name_off` indexes the start of a NUL-terminated name in `string_blob`.
//!
//! # In-memory
//!
//! [`FidDb`] holds the `lang_id`/`cspec_id` and the only hot-path index FID needs:
//! `by_full_hash: HashMap<u64, Vec<FidRecord>>` (Ghidra's `FULL_HASH_COL` index —
//! the analyzer queries by *full* hash only; the specific hash is a stored
//! tiebreak field, not an index). [`FidDb::find_by_full_hash`] is the single
//! query the matching pass (PR4) makes.
//!
//! # Robustness
//!
//! [`load`](FidDb::load) **never panics** on a malformed/truncated file — every
//! read is bounds-checked and a short/garbled input is an `Err`, never an
//! out-of-bounds index. This matters because a `.fid` path may be user-supplied.

use std::collections::HashMap;

use kuna_base::error::{KunaError, KunaResult};

/// `"KFID"` — the `.fid` file magic.
pub const FID_DB_MAGIC: &[u8; 4] = b"KFID";

/// The on-disk format version. **Bump on ANY change to the hash, the skipper
/// patterns, or the record layout** (Ghidra's `FidFileManager.VERSION = 6`
/// analog) — a mismatched version means the stored hashes were computed by a
/// different algorithm and would mis-match.
pub const FID_DB_VERSION: u32 = 1;

/// `flags` bit 0 — the record's hash was computed over a body with a terminator
/// (return/halt) as its last code unit. Reserved/stored for the PR5 seeker; the
/// rest of the byte is reserved (`auto_pass`/`auto_fail`/`force_*`).
pub const FLAG_HAS_TERMINATOR: u8 = 0x01;

/// One fingerprint record — a function's [`FidHashQuad`](crate::fid::hash::FidHashQuad)
/// plus its name and flags. The four hash fields mirror `FidHashQuadImpl`
/// field-for-field; `name` is resolved from the string blob at load time.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FidRecord {
    /// `fullHash` — the operand-masked, position/relocation-independent digest.
    /// This is the index key ([`FidDb::find_by_full_hash`]).
    pub full_hash: u64,
    /// `specificHash` — the digest that also folds usable scalar values (the
    /// disambiguating tiebreak; stored, not indexed, in v1).
    pub specific_hash: u64,
    /// `codeUnitSize` — the post-skip code-unit count minus calls (Ghidra
    /// `short`).
    pub code_unit_size: i16,
    /// `additionalSpecificCount` — `min(specificCount, 127)` (Ghidra `byte`).
    pub specific_addl: u8,
    /// Record flags ([`FLAG_HAS_TERMINATOR`] + reserved).
    pub flags: u8,
    /// The function name this fingerprint identifies (resolved from the interned
    /// string blob at load; interned back into it at serialize).
    pub name: String,
}

/// The database query seam. A `.fid` reader (this module) and a future `.fidbf`
/// reader (deferred PR6) both implement it, so the matching pass (PR4) is written
/// once against the trait and a format swap is a drop-in.
pub trait FidDatabase {
    /// The SLEIGH language id the database was built for; the matching pass
    /// refuses a program whose language id does not match (a hash is only
    /// comparable within one language).
    fn lang_id(&self) -> &str;
    /// The compiler-spec id the database was built for.
    fn cspec_id(&self) -> &str;
    /// All records whose `full_hash` equals `h` — FID's only hot-path query
    /// (`FidQueryService.findRecord` by `FULL_HASH_COL`). An empty slice means no
    /// match. The order is the records' insertion order (build order).
    fn find_by_full_hash(&self, h: u64) -> &[FidRecord];
    /// The total record count (diagnostics / tests).
    fn record_count(&self) -> usize;
}

/// The in-memory `.fid` database: the language/compiler ids and the full-hash
/// index. Built by [`FidDb::load`] (parse bytes) or [`FidDb::from_records`]
/// (the generator), serialized by [`FidDb::serialize`].
#[derive(Debug, Clone, Default)]
pub struct FidDb {
    lang_id: String,
    cspec_id: String,
    /// The `FULL_HASH_COL` index: `full_hash -> records sharing it`. A full hash
    /// can map to several functions (a genuine collision, or the same function
    /// under several names), which the PR4 matcher disambiguates.
    by_full_hash: HashMap<u64, Vec<FidRecord>>,
    /// The number of records (the `by_full_hash` buckets may merge collisions, so
    /// this is tracked separately for a faithful round-trip count).
    n_records: usize,
}

/// An empty slice returned for a full hash with no records (so `find_by_full_hash`
/// can return `&[]` without allocating).
const NO_RECORDS: &[FidRecord] = &[];

impl FidDb {
    /// Build a database directly from a record list (the generator path). Records
    /// are indexed by their `full_hash`; insertion order within a bucket is
    /// preserved.
    pub fn from_records(
        lang_id: impl Into<String>,
        cspec_id: impl Into<String>,
        records: Vec<FidRecord>,
    ) -> Self {
        let mut by_full_hash: HashMap<u64, Vec<FidRecord>> = HashMap::new();
        let n_records = records.len();
        for rec in records {
            by_full_hash.entry(rec.full_hash).or_default().push(rec);
        }
        Self { lang_id: lang_id.into(), cspec_id: cspec_id.into(), by_full_hash, n_records }
    }

    /// Every record, in a deterministic order (sorted by `full_hash`, then by the
    /// in-bucket order). Used by [`serialize`](Self::serialize) and by tests.
    pub fn records(&self) -> Vec<&FidRecord> {
        let mut keys: Vec<&u64> = self.by_full_hash.keys().collect();
        keys.sort_unstable();
        let mut out: Vec<&FidRecord> = Vec::with_capacity(self.n_records);
        for k in keys {
            out.extend(self.by_full_hash[k].iter());
        }
        out
    }

    /// Serialize to the on-disk `.fid` byte stream (§5.1). The string blob is
    /// interned: identical names share one entry. Records are written in the
    /// deterministic [`records`](Self::records) order so the output is
    /// reproducible.
    pub fn serialize(&self) -> Vec<u8> {
        let records = self.records();

        // Intern names into the blob, mapping each distinct name to its offset.
        let mut blob: Vec<u8> = Vec::new();
        let mut name_off: HashMap<&str, u32> = HashMap::new();
        for rec in &records {
            if !name_off.contains_key(rec.name.as_str()) {
                let off = blob.len() as u32;
                name_off.insert(rec.name.as_str(), off);
                blob.extend_from_slice(rec.name.as_bytes());
                blob.push(0); // NUL terminator
            }
        }

        let mut out: Vec<u8> = Vec::new();
        out.extend_from_slice(FID_DB_MAGIC);
        out.extend_from_slice(&FID_DB_VERSION.to_le_bytes());
        write_str(&mut out, &self.lang_id);
        write_str(&mut out, &self.cspec_id);
        out.extend_from_slice(&(records.len() as u32).to_le_bytes());
        for rec in &records {
            out.extend_from_slice(&rec.full_hash.to_le_bytes());
            out.extend_from_slice(&rec.specific_hash.to_le_bytes());
            out.extend_from_slice(&rec.code_unit_size.to_le_bytes());
            out.push(rec.specific_addl);
            out.push(rec.flags);
            out.extend_from_slice(&name_off[rec.name.as_str()].to_le_bytes());
        }
        out.extend_from_slice(&blob);
        out
    }

    /// Parse a `.fid` byte stream (§5.1). **Never panics**: a truncated or
    /// malformed input is an `Err`, every read bounds-checked. On success the
    /// records are indexed by `full_hash`.
    pub fn load(bytes: &[u8]) -> KunaResult<Self> {
        let mut r = Reader::new(bytes);

        let magic = r.take(4)?;
        if magic != FID_DB_MAGIC {
            return Err(KunaError::bad_data(format!(
                "fid: bad magic {magic:02x?} (expected {FID_DB_MAGIC:?})"
            )));
        }
        let version = r.u32()?;
        if version != FID_DB_VERSION {
            return Err(KunaError::bad_data(format!(
                "fid: version {version} != supported {FID_DB_VERSION}"
            )));
        }
        let lang_id = r.string()?;
        let cspec_id = r.string()?;
        let n = r.u32()? as usize;

        // Read the fixed-width record table, deferring name resolution until the
        // blob (which follows the table) is in hand.
        let mut raw: Vec<RawRecord> = Vec::with_capacity(n.min(1 << 20));
        for _ in 0..n {
            raw.push(RawRecord {
                full_hash: r.u64()?,
                specific_hash: r.u64()?,
                code_unit_size: r.i16()?,
                specific_addl: r.u8()?,
                flags: r.u8()?,
                name_off: r.u32()?,
            });
        }
        // The remainder is the string blob.
        let blob = r.rest();

        let mut records: Vec<FidRecord> = Vec::with_capacity(raw.len());
        for rr in raw {
            let name = read_interned_name(blob, rr.name_off as usize)?;
            records.push(FidRecord {
                full_hash: rr.full_hash,
                specific_hash: rr.specific_hash,
                code_unit_size: rr.code_unit_size,
                specific_addl: rr.specific_addl,
                flags: rr.flags,
                name,
            });
        }

        Ok(Self::from_records(lang_id, cspec_id, records))
    }
}

impl FidDatabase for FidDb {
    fn lang_id(&self) -> &str {
        &self.lang_id
    }
    fn cspec_id(&self) -> &str {
        &self.cspec_id
    }
    fn find_by_full_hash(&self, h: u64) -> &[FidRecord] {
        self.by_full_hash.get(&h).map(Vec::as_slice).unwrap_or(NO_RECORDS)
    }
    fn record_count(&self) -> usize {
        self.n_records
    }
}

/// The on-disk record before name resolution.
struct RawRecord {
    full_hash: u64,
    specific_hash: u64,
    code_unit_size: i16,
    specific_addl: u8,
    flags: u8,
    name_off: u32,
}

/// Write a length-prefixed (`u32` LE) UTF-8 string.
fn write_str(out: &mut Vec<u8>, s: &str) {
    out.extend_from_slice(&(s.len() as u32).to_le_bytes());
    out.extend_from_slice(s.as_bytes());
}

/// Read a NUL-terminated UTF-8 name from the blob at `off`. A bad offset or a
/// non-UTF-8 / unterminated name is an error (never a panic).
fn read_interned_name(blob: &[u8], off: usize) -> KunaResult<String> {
    if off > blob.len() {
        return Err(KunaError::bad_data(format!(
            "fid: name offset {off} past blob end {}",
            blob.len()
        )));
    }
    let tail = &blob[off..];
    let end = tail
        .iter()
        .position(|&b| b == 0)
        .ok_or_else(|| KunaError::bad_data("fid: unterminated name in string blob"))?;
    std::str::from_utf8(&tail[..end])
        .map(str::to_owned)
        .map_err(|_| KunaError::bad_data("fid: non-UTF-8 name in string blob"))
}

/// A bounds-checked little-endian byte reader. Every accessor returns `Err`
/// rather than panic on a short input — the load path must be robust to a
/// malformed/truncated `.fid`.
struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn new(buf: &'a [u8]) -> Self {
        Self { buf, pos: 0 }
    }

    fn take(&mut self, n: usize) -> KunaResult<&'a [u8]> {
        let end = self.pos.checked_add(n).ok_or_else(|| KunaError::bad_data("fid: length overflow"))?;
        if end > self.buf.len() {
            return Err(KunaError::bad_data(format!(
                "fid: truncated (need {n} bytes at {}, have {})",
                self.pos,
                self.buf.len()
            )));
        }
        let s = &self.buf[self.pos..end];
        self.pos = end;
        Ok(s)
    }

    fn u8(&mut self) -> KunaResult<u8> {
        Ok(self.take(1)?[0])
    }

    fn u32(&mut self) -> KunaResult<u32> {
        let b = self.take(4)?;
        Ok(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
    }

    fn u64(&mut self) -> KunaResult<u64> {
        let b = self.take(8)?;
        Ok(u64::from_le_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]]))
    }

    fn i16(&mut self) -> KunaResult<i16> {
        let b = self.take(2)?;
        Ok(i16::from_le_bytes([b[0], b[1]]))
    }

    /// A length-prefixed UTF-8 string (`u32` LE length + bytes).
    fn string(&mut self) -> KunaResult<String> {
        let len = self.u32()? as usize;
        let b = self.take(len)?;
        std::str::from_utf8(b)
            .map(str::to_owned)
            .map_err(|_| KunaError::bad_data("fid: non-UTF-8 length-prefixed string"))
    }

    /// The unconsumed remainder (the string blob).
    fn rest(&self) -> &'a [u8] {
        &self.buf[self.pos..]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rec(full: u64, spec: u64, cus: i16, addl: u8, name: &str) -> FidRecord {
        FidRecord {
            full_hash: full,
            specific_hash: spec,
            code_unit_size: cus,
            specific_addl: addl,
            flags: FLAG_HAS_TERMINATOR,
            name: name.to_string(),
        }
    }

    #[test]
    fn round_trip_preserves_records_and_index() {
        // Build a DB in memory, serialize, re-load, and assert the records +
        // find_by_full_hash match (the §-Tests round-trip gate).
        let records = vec![
            rec(0x1111_1111_1111_1111, 0xaaaa, 10, 3, "kuna_crc32"),
            rec(0x2222_2222_2222_2222, 0xbbbb, 7, 1, "kuna_strlen"),
            rec(0x3333_3333_3333_3333, 0xcccc, 5, 0, "kuna_memset"),
        ];
        let db = FidDb::from_records("x86:LE:64:default", "gcc", records.clone());

        let bytes = db.serialize();
        let back = FidDb::load(&bytes).expect("round-trip load");

        // Header fields survive.
        assert_eq!(back.lang_id(), "x86:LE:64:default");
        assert_eq!(back.cspec_id(), "gcc");
        assert_eq!(back.record_count(), 3);

        // Each record is found by its full hash with all fields intact.
        for want in &records {
            let got = back.find_by_full_hash(want.full_hash);
            assert_eq!(got.len(), 1, "one record per distinct full hash");
            assert_eq!(&got[0], want, "record survives round-trip byte-for-byte");
        }

        // A hash that is not present yields no records (no panic, empty slice).
        assert!(back.find_by_full_hash(0xdead_beef).is_empty());
    }

    #[test]
    fn collision_bucket_keeps_all_records() {
        // Two functions sharing a full hash both land in the same bucket and both
        // survive the round-trip.
        let records = vec![
            rec(0x4242, 0x1, 6, 2, "foo"),
            rec(0x4242, 0x2, 6, 2, "bar"),
        ];
        let db = FidDb::from_records("L", "C", records);
        let back = FidDb::load(&db.serialize()).unwrap();
        assert_eq!(back.record_count(), 2);
        let bucket = back.find_by_full_hash(0x4242);
        assert_eq!(bucket.len(), 2);
        let names: Vec<&str> = bucket.iter().map(|r| r.name.as_str()).collect();
        assert!(names.contains(&"foo") && names.contains(&"bar"));
    }

    #[test]
    fn names_are_interned() {
        // Two records with the same name share one blob entry — the serialized
        // size is smaller than if the name were stored twice, and both load back
        // to the same name.
        let dup = vec![rec(0x1, 0, 4, 0, "same"), rec(0x2, 0, 4, 0, "same")];
        let db = FidDb::from_records("L", "C", dup);
        let bytes = db.serialize();
        // "same\0" appears exactly once in the blob.
        let blob_count = bytes.windows(5).filter(|w| *w == b"same\0").count();
        assert_eq!(blob_count, 1, "the shared name is interned once");
        let back = FidDb::load(&bytes).unwrap();
        assert_eq!(back.find_by_full_hash(0x1)[0].name, "same");
        assert_eq!(back.find_by_full_hash(0x2)[0].name, "same");
    }

    #[test]
    fn empty_db_round_trips() {
        let db = FidDb::from_records("x86:LE:64:default", "gcc", vec![]);
        let back = FidDb::load(&db.serialize()).unwrap();
        assert_eq!(back.record_count(), 0);
        assert!(back.find_by_full_hash(0).is_empty());
    }

    // --- Malformed-input robustness (never panic → Err) ----------------------

    #[test]
    fn empty_input_is_error_not_panic() {
        assert!(FidDb::load(&[]).is_err());
    }

    #[test]
    fn bad_magic_is_error() {
        let mut bytes = FidDb::from_records("L", "C", vec![]).serialize();
        bytes[0] = b'X';
        assert!(FidDb::load(&bytes).is_err());
    }

    #[test]
    fn wrong_version_is_error() {
        let mut bytes = FidDb::from_records("L", "C", vec![]).serialize();
        // The version u32 starts right after the 4-byte magic.
        bytes[4] = bytes[4].wrapping_add(1);
        assert!(FidDb::load(&bytes).is_err());
    }

    #[test]
    fn truncated_record_table_is_error() {
        let db = FidDb::from_records("L", "C", vec![rec(0x1, 0x2, 4, 0, "x")]);
        let bytes = db.serialize();
        // Lop off the trailing half — the record table / blob is truncated.
        for cut in 1..bytes.len() {
            // Every truncation either errors or (for a prefix that happens to be a
            // valid empty-ish DB) loads — but it must NEVER panic.
            let _ = FidDb::load(&bytes[..cut]);
        }
    }

    #[test]
    fn bad_name_offset_is_error() {
        // Hand-craft a DB whose single record points its name_off past the blob.
        let mut bytes: Vec<u8> = Vec::new();
        bytes.extend_from_slice(FID_DB_MAGIC);
        bytes.extend_from_slice(&FID_DB_VERSION.to_le_bytes());
        // lang_id ""  cspec_id ""
        bytes.extend_from_slice(&0u32.to_le_bytes());
        bytes.extend_from_slice(&0u32.to_le_bytes());
        // n_records = 1
        bytes.extend_from_slice(&1u32.to_le_bytes());
        // the record: full|spec|cus|addl|flags|name_off=9999 (no blob follows)
        bytes.extend_from_slice(&0u64.to_le_bytes());
        bytes.extend_from_slice(&0u64.to_le_bytes());
        bytes.extend_from_slice(&0i16.to_le_bytes());
        bytes.push(0);
        bytes.push(0);
        bytes.extend_from_slice(&9999u32.to_le_bytes());
        // (no string blob)
        assert!(FidDb::load(&bytes).is_err());
    }
}
