//! End-to-end two-pass gate for `pdbinterior` (GH-468): a PDB procedure's code
//! length keeps the aggressive gap walk from starting a function inside it, but
//! only inside a procedure whose start is itself a function, and only where that
//! function's own flow decodes.
//!
//! Fixture: `pe_pdbinterior_x86_64.exe` + its sidecar `.pdb` (both generated by
//! `pe_pdbinterior_x86_64.py`). `_start` calls twenty `mov eax,imm ; mov edx,-1`
//! helpers, which clear AIF's 20-function floor and stock its fingerprint
//! histogram. `cascade_leaf` at `0x1400011c0` is called by nobody and has no
//! `.pdata` record, so only the PDB names it and recursive descent never decodes
//! it:
//!
//! ```text
//!   0x1400011c0  cmp ecx,0x2003 ; jg high ; jz ret_21
//!   0x1400011ca  cmp ecx,0x1000
//!   0x1400011d0  mov eax,10 ; mov edx,-1 ; cmovnz eax,edx ; ret   <- fall-through
//!   0x1400011de  ret_21: mov eax,0x21 ; ret
//!   0x1400011e4  high: cmp ecx,0x3007 ; mov eax,0x4d ; ... ; ret
//! ```
//!
//! **The bug** (`pdbinterior off`): the gap walk probes the leaf's aligned bytes,
//! and `0x1400011d0` opens with the helpers' `mov ; mov` fingerprint and runs to a
//! `ret`, so AIF accepts it. `funcboundflow` then ends `cascade_leaf` where its
//! fall-through reaches that entry, and the `0x1000 -> 10` case is gone.
//!
//! **The fix** (default): the `.pdb` records `cascade_leaf` as a 56-byte
//! procedure and publishes its name, so the entry strictly inside it is rejected
//! at the commit and the leaf decompiles whole.
//!
//! `static_leaf` at `0x140001340` is the same code as a `static` function: an
//! `S_LPROC32` record and no public, so the `pdb` pass does not admit its start
//! and the gap walk's `0x140001350` is the only function its code has. That entry
//! must survive the default, and is rejected only once a function exists at
//! `0x140001340`. The public `handler_leaf`, `caller_leaf` and `noreturn_leaf`
//! hold entries their own flow never decodes (`0x1400013a0`, after the last `ret`;
//! `0x1400013d0`, reached only by a call; `0x140001410`, past a call to `abort`),
//! which must survive as well. A copy of the image whose CodeView fingerprint no
//! longer matches the `.pdb` must commit exactly what `pdb off` commits.
//!
//! The discovery options are the ones `--mode aggressive` (the `auto` choice for
//! an image this small) turns on, set before the deferred commit as the CLI does.
//!
//! ## `.sla` precondition
//!
//! Bootstrapping needs the built x86 `.sla` under `specs/` (gitignored; `make
//! specs`). When it is absent the bootstrap fails; the test prints that and returns
//! early (a specs-less CI is a visible skip, never a false green).

use std::path::{Path, PathBuf};

use kuna_base::address::Address;
use kuna_console::engine::{bootstrap_from_object, ConsoleProgram};
use kuna_console::ifacedecomp::{
    execute, register_decomp_commands, IfaceDecompData, DECOMPILE_MODULE,
};
use kuna_console::ifaceterm::ConsoleCommands;

const LEAF: &str = "cascade_leaf";
const PHANTOM: &str = "sub_1400011d0";
const STATIC_LEAF: u64 = 0x140001340;
const STATIC_PHANTOM: &str = "sub_140001350";

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .canonicalize()
        .unwrap()
}

fn fixture(ext: &str) -> PathBuf {
    repo_root().join(format!(
        "decompiler/crates/kuna-analysis/tests/fixtures/pe_pdbinterior_x86_64.{ext}"
    ))
}

fn bootstrap(options: &[(&str, &str)]) -> Option<ConsoleProgram> {
    bootstrap_image(&fixture("exe"), options, None)
}

fn bootstrap_image(
    bin: &Path,
    options: &[(&str, &str)],
    declared: Option<(u64, &str)>,
) -> Option<ConsoleProgram> {
    let specs = repo_root().join("specs");
    let spec_roots = vec![specs.to_str().unwrap().to_string()];
    let mut prog = match bootstrap_from_object(bin.to_str().unwrap(), "", &spec_roots) {
        Ok(p) => p,
        Err(e) => {
            eprintln!(
                "verify_pdbinterior: skipping (bootstrap failed, build `.sla` with \
                 `make specs`): {}",
                e.explain()
            );
            return None;
        }
    };
    for (name, value) in [("listing", "on"), ("aif", "on"), ("aifstrict", "on")]
        .iter()
        .chain(options)
    {
        prog.arch_mut()
            .set_kuna_option(name, value)
            .expect("option applies");
    }
    if let Some((vma, name)) = declared {
        let space = prog
            .arch()
            .manage()
            .get_default_code_space()
            .cloned()
            .expect("code space");
        prog.declare_function(Address::new(space, vma), Some(name), 0)
            .expect("the declaration installs");
    }
    prog.commit_pending_analysis()
        .expect("analysis commit succeeds");
    Some(prog)
}

fn decompile(prog: ConsoleProgram, name: &str) -> String {
    let cmds: Vec<String> = vec![
        format!("load function {name}"),
        "decompile".into(),
        "print C".into(),
    ];
    let count = cmds.len();
    let mut status = ConsoleCommands::into_status(cmds);
    register_decomp_commands(&mut status);
    {
        let data = status.get_data_mut(DECOMPILE_MODULE).unwrap();
        let dcp = data.as_any_mut().downcast_mut::<IfaceDecompData>().unwrap();
        dcp.conf = Some(prog);
    }
    for _ in 0..count {
        execute(&mut status);
    }
    status.optr.clone()
}

fn has_all_cases(body: &str) -> bool {
    ["0x2003", "0x1000", "0x3007"]
        .iter()
        .all(|k| body.contains(k))
        && body.contains("return 10")
}

fn has_all_static_cases(body: &str) -> bool {
    ["0x5000", "0x6003", "0x7007"]
        .iter()
        .all(|k| body.contains(k))
        && body.contains("return 0x14")
}

fn inventory(prog: &ConsoleProgram) -> Vec<(u64, String, Vec<String>)> {
    prog.function_entries_canonical()
        .into_iter()
        .map(|e| (e.addr.get_offset(), e.name, e.aliases))
        .collect()
}

/// BEFORE (`--option pdbinterior off`): the gap walk's entry inside the leaf is
/// committed and the leaf's render stops at it.
#[test]
fn off_plants_an_entry_inside_the_pdb_leaf() {
    let Some(prog) = bootstrap(&[("pdbinterior", "off")]) else {
        return;
    };
    assert!(prog.lookup_symbol(LEAF).is_some(), "the PDB names the leaf");
    assert!(
        prog.lookup_symbol(PHANTOM).is_some(),
        "with pdbinterior off the gap walk's {PHANTOM} must still be committed"
    );
    let body = decompile(prog, LEAF);
    assert!(
        body.contains("funcboundflow") && !has_all_cases(&body),
        "the leaf must be truncated at {PHANTOM} and lose its 0x1000 case; got:\n{body}"
    );
}

/// AFTER (default): the PDB procedure bounds the leaf, the interior entry is
/// rejected and every case renders.
#[test]
fn default_keeps_the_pdb_leaf_whole() {
    let Some(prog) = bootstrap(&[]) else {
        return;
    };
    assert!(prog.lookup_symbol(LEAF).is_some(), "the PDB names the leaf");
    assert!(
        prog.lookup_symbol(PHANTOM).is_none(),
        "{PHANTOM} is strictly inside cascade_leaf's PDB procedure and must be rejected"
    );
    for helper in ["pick_00", "pick_09", "pick_10", "pick_19"] {
        assert!(
            prog.lookup_symbol(helper).is_some(),
            "{helper} must survive"
        );
    }
    let body = decompile(prog, LEAF);
    assert!(
        !body.contains("funcboundflow") && has_all_cases(&body),
        "the leaf must decompile whole, all three cases; got:\n{body}"
    );
}

/// The extents come out of the `.pdb`, so `pdb off` withdraws them as well.
#[test]
fn pdb_off_withdraws_the_extents() {
    let Some(prog) = bootstrap(&[("pdb", "off")]) else {
        return;
    };
    assert!(
        prog.lookup_symbol(PHANTOM).is_some(),
        "with pdb off nothing may consult the .pdb, so {PHANTOM} is committed as before"
    );
}

/// A `static` function's procedure has no public, so nothing admits its start;
/// the entry inside it is the only function its code has, and it stays.
#[test]
fn default_keeps_the_only_entry_of_a_static_leaf() {
    let Some(prog) = bootstrap(&[]) else {
        return;
    };
    assert!(
        prog.lookup_symbol("static_leaf").is_none(),
        "no public names the static leaf"
    );
    let starts: Vec<u64> = inventory(&prog).iter().map(|e| e.0).collect();
    assert!(
        !starts.contains(&STATIC_LEAF),
        "nothing discovers the static leaf's start"
    );
    assert!(
        prog.lookup_symbol(STATIC_PHANTOM).is_some(),
        "{STATIC_PHANTOM} is the static leaf's only function and must be committed"
    );
    let body = decompile(prog, STATIC_PHANTOM);
    assert!(
        body.contains("return 0x14"),
        "its code must still render; got:\n{body}"
    );
}

/// Once a function exists at the static leaf's start, its extent applies: off
/// truncates the declared function at the gap walk's entry, the default rejects
/// that entry and renders every case.
#[test]
fn a_function_at_the_static_leaf_start_lets_its_extent_apply() {
    let declared = Some((STATIC_LEAF, "static_leaf"));
    let Some(off) = bootstrap_image(&fixture("exe"), &[("pdbinterior", "off")], declared) else {
        return;
    };
    assert!(
        off.lookup_symbol(STATIC_PHANTOM).is_some(),
        "off commits {STATIC_PHANTOM}"
    );
    let body = decompile(off, "static_leaf");
    assert!(
        body.contains("funcboundflow") && !has_all_static_cases(&body),
        "off must truncate static_leaf at {STATIC_PHANTOM}; got:\n{body}"
    );

    let Some(on) = bootstrap_image(&fixture("exe"), &[], declared) else {
        return;
    };
    assert!(
        on.lookup_symbol(STATIC_PHANTOM).is_none(),
        "{STATIC_PHANTOM} must be rejected"
    );
    let body = decompile(on, "static_leaf");
    assert!(
        !body.contains("funcboundflow") && has_all_static_cases(&body),
        "static_leaf must decompile whole; got:\n{body}"
    );
}

/// Code a public procedure's own flow never decodes keeps its gap-walk entry:
/// a block after `handler_leaf`'s last `ret` (where a jump-table case or an
/// exception handler would sit), the routine `caller_leaf` only calls, and the
/// block after `noreturn_leaf`'s call to `abort`, which the decompiler stops at.
/// Every entry exists with the option off, so the default is what keeps them.
#[test]
fn default_keeps_entries_the_owner_does_not_decode() {
    for options in [&[("pdbinterior", "off")][..], &[]] {
        let Some(prog) = bootstrap(options) else {
            return;
        };
        for (leaf, entry) in [
            ("handler_leaf", "sub_1400013a0"),
            ("caller_leaf", "sub_1400013d0"),
            ("noreturn_leaf", "sub_140001410"),
        ] {
            assert!(prog.lookup_symbol(leaf).is_some(), "the PDB names {leaf}");
            assert!(
                prog.lookup_symbol(entry).is_some(),
                "{entry} inside {leaf} must stay committed with {options:?}"
            );
        }
    }
}

/// The walk cannot prove a call with no static target returns, so it does not
/// claim the block after it. `indirect_leaf` calls through a memory slot and
/// `fastfail_leaf` runs `int 0x29`; the gap-walk entry after each stays under the
/// default (removing it would render that block nowhere — the #612 defect class).
#[test]
fn default_keeps_entries_after_a_targetless_call() {
    let Some(prog) = bootstrap(&[]) else {
        return;
    };
    for (leaf, entry) in
        [("indirect_leaf", "sub_140001450"), ("fastfail_leaf", "sub_140001490")]
    {
        assert!(prog.lookup_symbol(leaf).is_some(), "the PDB names {leaf}");
        assert!(
            prog.lookup_symbol(entry).is_some(),
            "{entry} after {leaf}'s targetless call must stay: nothing else renders it"
        );
    }
}

/// A public strictly inside a procedure marks a function boundary the extent may
/// not swallow: `pubinside_leaf` carries an `S_PUB32` at its interior, so its
/// extent is not used and the public survives.
#[test]
fn a_public_inside_a_procedure_blocks_its_extent() {
    let Some(prog) = bootstrap(&[]) else {
        return;
    };
    assert!(prog.lookup_symbol("pubinside_leaf").is_some(), "the PDB names pubinside_leaf");
    assert!(
        prog.lookup_symbol("pub_inside").is_some(),
        "the interior public must survive (its procedure's extent is not usable)"
    );
}

/// A `.pdb` from another build (the image's CodeView age no longer matches)
/// changes nothing: the default commits exactly the `pdb off` inventory.
#[test]
fn a_fingerprint_mismatched_pdb_changes_nothing() {
    let dir = std::env::temp_dir().join(format!("kuna-verify-pdbinterior-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("scratch dir");
    let exe = dir.join("pe_pdbinterior_x86_64.exe");
    std::fs::copy(fixture("pdb"), dir.join("pe_pdbinterior_x86_64.pdb")).expect("copy pdb");
    let mut bytes = std::fs::read(fixture("exe")).expect("read exe");
    let rsds = bytes
        .windows(4)
        .position(|w| w == b"RSDS")
        .expect("RSDS record");
    bytes[rsds + 20] += 1;
    std::fs::write(&exe, &bytes).expect("write the stale-fingerprint copy");

    let default = bootstrap_image(&exe, &[], None);
    let pdb_off = bootstrap_image(&exe, &[("pdb", "off")], None);
    let _ = std::fs::remove_dir_all(&dir);
    let (Some(default), Some(pdb_off)) = (default, pdb_off) else {
        return;
    };
    assert!(
        default.lookup_symbol(PHANTOM).is_some(),
        "no extent may apply"
    );
    assert!(
        default.lookup_symbol(LEAF).is_none(),
        "no PDB name may apply"
    );
    assert_eq!(inventory(&default), inventory(&pdb_off));
}
