//! FID PR4 end-to-end gate — THE PAYOFF: re-identify a function in a STRIPPED
//! x86-64 binary by full-hash fingerprint.
//!
//! Fixture: `tests/fixtures/fid/prog` — a statically-linked, `-no-pie`, **stripped**
//! x86-64 ELF built from `lib.c` (`kuna_crc32`/`kuna_strlen`/`kuna_memset`) + a
//! `main.c` that calls each (so the linker retains them). `strip --strip-all` left
//! NO symbol table, so every function is an engine `FUN_*`/`sub_*` placeholder. The
//! star function `kuna_crc32` is at VMA `0x4017c0` (the CRC-32 loop with the magic
//! `0xEDB88320` immediate). The build recipe + the pinned VMA are recorded in
//! `tests/fixtures/fid/README.md`.
//!
//! The fingerprint database `tests/fixtures/fid/lib.fid` was generated by
//! `kuna fid build` over the (un-stripped) `lib.o` (FID PR3) — the three function
//! fingerprints, vendored tiny.
//!
//! ## The two-state proof (`docs/fid-design.md` §7.2)
//!
//!  - **`--option fid off`** (default): the function at `0x4017c0` in the stripped
//!    `prog` carries an engine `sub_<addr>`/`FUN_*` placeholder name — proving the
//!    name is NOT a leftover symbol (the binary is stripped) and that FID's value is
//!    what's visible.
//!  - **`--option listing on --option fid on`** + `kuna_fid_db=…/lib.fid`: the SAME
//!    function is now **`kuna_crc32`** — recovered purely by full-hash fingerprint
//!    match against the library DB. Only FID could do this.
//!
//! The proof is read two ways: (1) the symbol-table name at `0x4017c0` (the rename
//! ground truth) and (2) the decompiled C (the name renders in the body). Both run
//! on the real-ELF path (loading an actual ELF), so the XML datatest 675/158 oracles
//! never reach this.
//!
//! ## `.sla` precondition
//!
//! Bootstrapping needs the built x86 `.sla` under `specs/` (gitignored; `make
//! specs`). When it is absent the bootstrap fails; the test prints that and returns
//! early (a specs-less CI is a visible skip, never a false green).

use std::path::PathBuf;
use std::rc::Rc;
use std::time::{Duration, Instant};

use kuna_base::address::Address;
use kuna_console::engine::{bootstrap_from_object, ConsoleProgram};
use kuna_console::ifacedecomp::{execute, register_decomp_commands, IfaceDecompData, DECOMPILE_MODULE};
use kuna_console::ifaceterm::ConsoleCommands;

/// The pinned VMA of `kuna_crc32` in the stripped `prog` (recorded in the fixture
/// README; `-static -no-pie` keeps it stable).
const KUNA_CRC32_VMA: u64 = 0x4017c0;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..").canonicalize().unwrap()
}

fn fixture_dir() -> PathBuf {
    repo_root().join("tests/fixtures/fid")
}

/// Whether to enable the FID matcher (and the Listing it reads + the DB env var).
enum Mode {
    /// Default: no flags, no DB env (the today baseline — the stripped placeholder).
    Off,
    /// `--option listing on --option fid on` + `kuna_fid_db=…/lib.fid`, set BEFORE
    /// the deferred commit (the live-CLI ordering).
    On,
}

/// The result of a run: the symbol-table name at `0x4017c0` (the rename ground
/// truth), the decompiled C of that function, and the wall-clock decompile time.
struct Run {
    name: String,
    body: String,
    dur: Duration,
}

/// Resolve the symbol-table name at `KUNA_CRC32_VMA` (the engine placeholder, or the
/// FID-installed library name).
fn name_at_crc32(prog: &ConsoleProgram) -> String {
    let code_space = prog
        .arch()
        .manage()
        .get_default_code_space()
        .expect("a default code space")
        .clone();
    let addr = Address::new(Rc::clone(&code_space), KUNA_CRC32_VMA);
    match prog.arch().symboltab.find_function_across_scopes(&addr) {
        Some((sid, _)) => prog.arch().symboltab.symbol(sid).get_name().to_string(),
        // No installed function symbol at the VMA ⇒ the engine default name.
        None => prog.arch().name_function(&addr),
    }
}

/// Bootstrap the stripped `prog`, (optionally) enable FID + point it at the DB,
/// resolve + decompile the function at `KUNA_CRC32_VMA`. `None` ⇒ specs-less skip.
fn run(mode: Mode) -> Option<Run> {
    let root = repo_root();
    let specs = root.join("specs");
    let spec_roots = vec![specs.to_str().unwrap().to_string()];

    let bin = fixture_dir().join("prog");
    let bin = bin.to_str()?.to_string();

    // The DB env var (`kuna_fid_db`) is read by `FidPass::run` at the deferred
    // commit. Set it ONLY for the On run; clear it for Off so the default path is
    // doubly inert (gate off AND no DB).
    match mode {
        Mode::On => {
            let db = fixture_dir().join("lib.fid");
            std::env::set_var("kuna_fid_db", db.to_str().unwrap());
        }
        Mode::Off => std::env::remove_var("kuna_fid_db"),
    }

    let mut prog = match bootstrap_from_object(&bin, "", &spec_roots) {
        Ok(p) => p,
        Err(e) => {
            eprintln!(
                "verify_fid: skipping (bootstrap failed, build `.sla` with \
                 `make specs`): {}",
                e.explain()
            );
            return None;
        }
    };

    // Live-CLI ordering: the `option` lines precede `read symbols` (the deferred
    // commit). Set the flags on the live arch BEFORE committing so the deferred
    // Listing build + FID consumer run see them on.
    if let Mode::On = mode {
        prog.arch_mut().set_kuna_option("listing", "on").expect("listing flips on");
        prog.arch_mut().set_kuna_option("fid", "on").expect("fid flips on");
    }
    // `read symbols`: build the Listing (deferred) + run the FID consumer, gated.
    prog.commit_pending_analysis().expect("analysis commit succeeds");

    // The rename ground truth: the symbol-table name at the VMA after the commit.
    let name = name_at_crc32(&prog);

    // Drive the decompile so the rendered body reflects the symbol name: when FID
    // re-identified the function it is now a real symbol resolvable by name (`load
    // function kuna_crc32`); the un-renamed placeholder is loaded by address (`load
    // addr 0x<vma>`, which names it via `name_function`). `load function` resolves
    // the installed symbol — including the FID-renamed one — so the body renders the
    // recovered name; `IfcAddrrangeLoad` builds a fresh default-named funcdata and
    // would not.
    let load_cmd = if is_placeholder(&name) {
        format!("load addr 0x{KUNA_CRC32_VMA:x}")
    } else {
        format!("load function {name}")
    };
    let cmds: Vec<String> = [load_cmd, "decompile".into(), "print C".into()].to_vec();
    let count = cmds.len();
    let mut status = ConsoleCommands::into_status(cmds);
    register_decomp_commands(&mut status);
    {
        let data = status.get_data_mut(DECOMPILE_MODULE).unwrap();
        let dcp = data.as_any_mut().downcast_mut::<IfaceDecompData>().unwrap();
        dcp.conf = Some(prog);
    }
    let t0 = Instant::now();
    for _ in 0..count {
        execute(&mut status);
    }
    let dur = t0.elapsed();
    Some(Run { name, body: status.optr.clone(), dur })
}

/// THE PAYOFF: the function at `0x4017c0` in the STRIPPED `prog` is a generic
/// `sub_*`/`FUN_*` placeholder by default, and becomes `kuna_crc32` only when FID is
/// on — recovered purely by full-hash fingerprint match against `lib.fid`.
#[test]
fn fid_reidentifies_stripped_crc32_by_fingerprint() {
    let Some(off) = run(Mode::Off) else {
        return; // specs-less skip
    };
    let on = run(Mode::On).expect("second bootstrap succeeds if the first did");

    eprintln!(
        "==== 0x{KUNA_CRC32_VMA:x} symbol  OFF: {:>16}   ON: {:>16} ====",
        off.name, on.name
    );
    eprintln!("---- FID OFF (default) [{:?}] ----\n{}", off.dur, off.body);
    eprintln!("---- FID ON [{:?}] ----\n{}", on.dur, on.body);

    // 1. FID OFF (default): the stripped function's name is a generic engine
    //    placeholder (`sub_*`/`FUN_*`/`func_*`) — NOT `kuna_crc32` (the binary is
    //    stripped; there is no symbol to leak it).
    assert!(
        is_placeholder(&off.name),
        "default (FID off) must leave 0x4017c0 a generic placeholder, got `{}`",
        off.name
    );
    assert_ne!(
        off.name, "kuna_crc32",
        "default (FID off) must NOT name the stripped function kuna_crc32 \
         (proves the name is not a leftover symbol)"
    );
    assert!(
        !off.body.contains("kuna_crc32"),
        "default (FID off) body must not render kuna_crc32:\n{}",
        off.body
    );

    // 2. FID ON: the SAME function is now `kuna_crc32`, recovered by fingerprint —
    //    in the symbol table AND in the rendered body.
    assert_eq!(
        on.name, "kuna_crc32",
        "FID on must rename 0x4017c0 to kuna_crc32 by full-hash match (symbol table)"
    );
    assert!(
        on.body.contains("kuna_crc32"),
        "FID on body must render the re-identified name kuna_crc32:\n{}",
        on.body
    );

    // 3. The symbol name changed — FID performed the rename.
    assert_ne!(
        off.name, on.name,
        "FID must change the function's name (the placeholder -> kuna_crc32 rename)"
    );
}

/// The default path is byte-identical regardless of how it is reached: with NO FID
/// flags the function stays a placeholder (the FID consumer never fires by default).
#[test]
fn fid_off_is_the_today_baseline() {
    let Some(off) = run(Mode::Off) else {
        return; // specs-less skip
    };
    assert!(is_placeholder(&off.name), "default name must be a placeholder, got `{}`", off.name);
    assert_ne!(off.name, "kuna_crc32", "default must not re-identify the stripped function");
    assert!(!off.body.trim().is_empty(), "expected a non-empty body for the crc32 function");
}

/// Is `name` an engine-generated placeholder (`sub_*`/`func_*`/`FUN_*`/`LAB_*`)?
fn is_placeholder(name: &str) -> bool {
    name.starts_with("sub_")
        || name.starts_with("func_")
        || name.starts_with("FUN_")
        || name.starts_with("LAB_")
}
