//! End-to-end two-pass gate for `pdbinterior` (GH-468): a PDB procedure's code
//! length keeps the aggressive gap walk from starting a function inside it.
//!
//! Fixture: `pe_pdbinterior_x86_64.exe` + its sidecar `.pdb` (both generated by
//! `pe_pdbinterior_x86_64.py`). `_start` calls twenty `mov eax,imm ; mov edx,-1`
//! helpers, which clear AIF's 20-function floor and stock its fingerprint
//! histogram. `cascade_leaf` at `0x1400011c0` is called by nobody and has no
//! `.pdata` record, so only the PDB names it and recursive descent never decodes
//! it:
//!
//! ```text
//!   0x1400011c0  cmp ecx,0x2003 ; jg high ; jz ret_21
//!   0x1400011ca  cmp ecx,0x1000
//!   0x1400011d0  mov eax,10 ; mov edx,-1 ; cmovnz eax,edx ; ret   <- fall-through
//!   0x1400011de  ret_21: mov eax,0x21 ; ret
//!   0x1400011e4  high: cmp ecx,0x3007 ; mov eax,0x4d ; ... ; ret
//! ```
//!
//! **The bug** (`pdbinterior off`): the gap walk probes the leaf's aligned bytes,
//! and `0x1400011d0` opens with the helpers' `mov ; mov` fingerprint and runs to a
//! `ret`, so AIF accepts it. `funcboundflow` then ends `cascade_leaf` where its
//! fall-through reaches that entry, and the `0x1000 -> 10` case is gone.
//!
//! **The fix** (default): the `.pdb` records `cascade_leaf` as a 56-byte
//! procedure, so the entry strictly inside it is rejected at the commit and the
//! leaf decompiles whole.
//!
//! The discovery options are the ones `--mode aggressive` (the `auto` choice for
//! an image this small) turns on, set before the deferred commit as the CLI does.
//!
//! ## `.sla` precondition
//!
//! Bootstrapping needs the built x86 `.sla` under `specs/` (gitignored; `make
//! specs`). When it is absent the bootstrap fails; the test prints that and returns
//! early (a specs-less CI is a visible skip, never a false green).

use std::path::PathBuf;

use kuna_console::engine::{bootstrap_from_object, ConsoleProgram};
use kuna_console::ifacedecomp::{
    execute, register_decomp_commands, IfaceDecompData, DECOMPILE_MODULE,
};
use kuna_console::ifaceterm::ConsoleCommands;

const LEAF: &str = "cascade_leaf";
const PHANTOM: &str = "sub_1400011d0";

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..").canonicalize().unwrap()
}

fn bootstrap(options: &[(&str, &str)]) -> Option<ConsoleProgram> {
    let bin = repo_root()
        .join("decompiler/crates/kuna-analysis/tests/fixtures/pe_pdbinterior_x86_64.exe");
    let specs = repo_root().join("specs");
    let spec_roots = vec![specs.to_str().unwrap().to_string()];
    let mut prog = match bootstrap_from_object(bin.to_str().unwrap(), "", &spec_roots) {
        Ok(p) => p,
        Err(e) => {
            eprintln!(
                "verify_pdbinterior: skipping (bootstrap failed, build `.sla` with \
                 `make specs`): {}",
                e.explain()
            );
            return None;
        }
    };
    for (name, value) in [("listing", "on"), ("aif", "on"), ("aifstrict", "on")]
        .iter()
        .chain(options)
    {
        prog.arch_mut().set_kuna_option(name, value).expect("option applies");
    }
    prog.commit_pending_analysis().expect("analysis commit succeeds");
    Some(prog)
}

fn decompile(prog: ConsoleProgram, name: &str) -> String {
    let cmds: Vec<String> =
        vec![format!("load function {name}"), "decompile".into(), "print C".into()];
    let count = cmds.len();
    let mut status = ConsoleCommands::into_status(cmds);
    register_decomp_commands(&mut status);
    {
        let data = status.get_data_mut(DECOMPILE_MODULE).unwrap();
        let dcp = data.as_any_mut().downcast_mut::<IfaceDecompData>().unwrap();
        dcp.conf = Some(prog);
    }
    for _ in 0..count {
        execute(&mut status);
    }
    status.optr.clone()
}

fn has_all_cases(body: &str) -> bool {
    ["0x2003", "0x1000", "0x3007"].iter().all(|k| body.contains(k)) && body.contains("return 10")
}

/// BEFORE (`--option pdbinterior off`): the gap walk's entry inside the leaf is
/// committed and the leaf's render stops at it.
#[test]
fn off_plants_an_entry_inside_the_pdb_leaf() {
    let Some(prog) = bootstrap(&[("pdbinterior", "off")]) else {
        return;
    };
    assert!(prog.lookup_symbol(LEAF).is_some(), "the PDB names the leaf");
    assert!(
        prog.lookup_symbol(PHANTOM).is_some(),
        "with pdbinterior off the gap walk's {PHANTOM} must still be committed"
    );
    let body = decompile(prog, LEAF);
    assert!(
        body.contains("funcboundflow") && !has_all_cases(&body),
        "the leaf must be truncated at {PHANTOM} and lose its 0x1000 case; got:\n{body}"
    );
}

/// AFTER (default): the PDB procedure bounds the leaf, the interior entry is
/// rejected and every case renders.
#[test]
fn default_keeps_the_pdb_leaf_whole() {
    let Some(prog) = bootstrap(&[]) else {
        return;
    };
    assert!(prog.lookup_symbol(LEAF).is_some(), "the PDB names the leaf");
    assert!(
        prog.lookup_symbol(PHANTOM).is_none(),
        "{PHANTOM} is strictly inside cascade_leaf's PDB procedure and must be rejected"
    );
    for helper in ["pick_00", "pick_09", "pick_10", "pick_19"] {
        assert!(prog.lookup_symbol(helper).is_some(), "{helper} must survive");
    }
    let body = decompile(prog, LEAF);
    assert!(
        !body.contains("funcboundflow") && has_all_cases(&body),
        "the leaf must decompile whole, all three cases; got:\n{body}"
    );
}

/// The extents come out of the `.pdb`, so `pdb off` withdraws them as well.
#[test]
fn pdb_off_withdraws_the_extents() {
    let Some(prog) = bootstrap(&[("pdb", "off")]) else {
        return;
    };
    assert!(
        prog.lookup_symbol(PHANTOM).is_some(),
        "with pdb off nothing may consult the .pdb, so {PHANTOM} is committed as before"
    );
}
