//! Generate the phase tables and string-valued option storage from `phases.toml`.

use std::fmt::Write as _;

#[path = "build/registry.rs"]
mod registry;
use registry::{Group, Registry, Settable, Subphase, Surface};

#[cfg(not(test))]
fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let toml_path = std::path::Path::new(&manifest_dir).join("phases.toml");
    println!("cargo:rerun-if-changed=phases.toml");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build/registry.rs");

    let text = std::fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", toml_path.display()));
    let out = generate(&text).unwrap_or_else(|e| panic!("phases.toml: {e}"));
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = std::path::Path::new(&out_dir).join("phases_generated.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

fn generate(text: &str) -> Result<String, toml::de::Error> {
    let registry: Registry = toml::from_str(text)?;
    let mut out = String::from("// @generated by build.rs from phases.toml -- DO NOT EDIT.\n\n");
    gen_groups(&mut out, &registry.group);
    gen_subphases(&mut out, &registry.subphase);
    gen_surfaces(&mut out, &registry.surface);
    gen_settables(&mut out, &registry.settable);
    gen_option_values(&mut out, &registry.settable);
    Ok(out)
}

/// Render a phase code ("P0".."P9" or "infra") as a `KunaPhase` variant path.
fn phase_variant(code: &str) -> String {
    let v = match code {
        "infra" => "Infra",
        "P0" => "P0",
        "P1" => "P1",
        "P2" => "P2",
        "P3" => "P3",
        "P4" => "P4",
        "P5" => "P5",
        "P6" => "P6",
        "P7" => "P7",
        "P8" => "P8",
        "P9" => "P9",
        other => panic!("phases.toml: bad phase code `{other}`"),
    };
    format!("KunaPhase::{v}")
}

/// Render a strength code ("NONE"/"HINT"/"HARD") as a `KunaStrength` variant.
fn strength_variant(code: &str) -> String {
    let v = match code {
        "NONE" => "None",
        "HINT" => "Hint",
        "HARD" => "Hard",
        other => panic!("phases.toml: bad strength code `{other}`"),
    };
    format!("KunaStrength::{v}")
}

/// Escape a string for a Rust string literal.
fn rlit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn gen_groups(out: &mut String, rows: &[Group]) {
    writeln!(
        out,
        "/// groupTable: every action/rule group name -> its dominant phase."
    )
    .unwrap();
    writeln!(
        out,
        "pub static GROUP_TABLE: [KunaGroupEntry; {}] = [",
        rows.len()
    )
    .unwrap();
    for r in rows {
        writeln!(
            out,
            "    KunaGroupEntry {{ group: {}, phase: {}, subphase: {}, note: {} }},",
            rlit(r.group.as_str()),
            phase_variant(r.phase.as_str()),
            rlit(r.subphase.as_str()),
            rlit(r.note.as_str()),
        )
        .unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

fn gen_subphases(out: &mut String, rows: &[Subphase]) {
    writeln!(out, "/// subphaseTable: every named decision point.").unwrap();
    writeln!(
        out,
        "pub static SUBPHASE_TABLE: [KunaSubPhase; {}] = [",
        rows.len()
    )
    .unwrap();
    for r in rows {
        writeln!(
            out,
            "    KunaSubPhase {{ name: {}, phase: {}, decision: {}, assertion: {}, strength: {}, rewind: {}, latent: {}, exposure: {} }},",
            rlit(r.name.as_str()),
            phase_variant(r.phase.as_str()),
            rlit(r.decision.as_str()),
            rlit(r.assertion.as_str()),
            strength_variant(r.strength.as_str()),
            phase_variant(r.rewind.as_str()),
            r.latent,
            rlit(r.exposure.as_str()),
        )
        .unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

fn gen_surfaces(out: &mut String, rows: &[Surface]) {
    writeln!(
        out,
        "/// surfaceTable: existing console/option surface -> the sub-phase it operates."
    )
    .unwrap();
    writeln!(
        out,
        "pub static SURFACE_TABLE: [KunaSurfaceEntry; {}] = [",
        rows.len()
    )
    .unwrap();
    for r in rows {
        writeln!(
            out,
            "    KunaSurfaceEntry {{ surface: {}, phase: {}, subphase: {}, note: {} }},",
            rlit(r.surface.as_str()),
            phase_variant(r.phase.as_str()),
            rlit(r.subphase.as_str()),
            rlit(r.note.as_str()),
        )
        .unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

fn gen_settables(out: &mut String, rows: &[Settable]) {
    writeln!(
        out,
        "/// settableTable: one row per kuna ArchOption -- the LLM control surface."
    )
    .unwrap();
    writeln!(
        out,
        "pub static SETTABLE_TABLE: [KunaSettable; {}] = [",
        rows.len()
    )
    .unwrap();
    for r in rows {
        writeln!(out, "    KunaSettable {{").unwrap();
        writeln!(out, "        option: {},", rlit(r.option.as_str())).unwrap();
        writeln!(out, "        values: {},", rlit(r.values.as_str())).unwrap();
        writeln!(out, "        shipped: {},", rlit(r.default.as_str())).unwrap();
        writeln!(out, "        destructive: {},", r.destructive).unwrap();
        writeln!(out, "        phase: {},", phase_variant(r.phase.as_str())).unwrap();
        writeln!(out, "        subphase: {},", rlit(r.subphase.as_str())).unwrap();
        writeln!(
            out,
            "        strength: {},",
            strength_variant(r.strength.as_str())
        )
        .unwrap();
        writeln!(out, "        rewind: {},", phase_variant(r.rewind.as_str())).unwrap();
        writeln!(out, "        issue: {},", rlit(r.issue.as_str())).unwrap();
        writeln!(out, "        summary: {},", rlit(r.summary.as_str())).unwrap();
        writeln!(out, "        use_when: {},", rlit(r.use_when.as_str())).unwrap();
        writeln!(out, "        example: {},", rlit(r.example.as_str())).unwrap();
        writeln!(
            out,
            "        source_decompiler: {},",
            rlit(r.source_decompiler.as_str())
        )
        .unwrap();
        writeln!(
            out,
            "        inspiration: {},",
            rlit(r.inspiration.as_str())
        )
        .unwrap();
        writeln!(
            out,
            "        change_kind: {},",
            rlit(r.change_kind.as_str())
        )
        .unwrap();
        let tier = r.tier.as_str();
        match tier {
            "core" | "transform" | "analysis" => {}
            other => panic!("phases.toml: bad tier `{other}` (need core|transform|analysis)"),
        }
        writeln!(out, "        tier: {},", rlit(tier)).unwrap();
        writeln!(out, "        symptoms: {},", rlit(r.symptoms.as_str())).unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

/// Turn an option name into a valid Rust field/ident (kebab/option names are
/// already lower_snake-safe here, but normalize defensively).
fn ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// Generate current-value storage, defaults, accessors, and live flag mappings.
fn gen_option_values(out: &mut String, rows: &[Settable]) {
    writeln!(
        out,
        "/// Current option values, initialized from the catalog's shipped defaults."
    )
    .unwrap();
    writeln!(out, "#[derive(Clone, Debug, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub struct OptionValues {{").unwrap();
    for r in rows {
        let opt = r.option.as_str();
        writeln!(
            out,
            "    /// Current value of `{}` (allowed: {}).",
            opt,
            r.values.as_str()
        )
        .unwrap();
        writeln!(out, "    pub {}: String,", ident(opt)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();

    writeln!(out, "impl Default for OptionValues {{").unwrap();
    writeln!(out, "    fn default() -> Self {{").unwrap();
    writeln!(out, "        OptionValues {{").unwrap();
    for r in rows {
        let opt = r.option.as_str();
        let def = r.default.as_str();
        writeln!(
            out,
            "            {}: {}.to_string(),",
            ident(opt),
            rlit(def)
        )
        .unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();

    writeln!(out, "impl OptionValues {{").unwrap();
    writeln!(
        out,
        "    /// Get a settable's current value by option name (None if unknown)."
    )
    .unwrap();
    writeln!(
        out,
        "    pub fn get(&self, option: &str) -> Option<&str> {{"
    )
    .unwrap();
    writeln!(out, "        match option {{").unwrap();
    for r in rows {
        let opt = r.option.as_str();
        writeln!(
            out,
            "            {} => Some(self.{}.as_str()),",
            rlit(opt),
            ident(opt)
        )
        .unwrap();
    }
    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    writeln!(
        out,
        "    /// Set a settable's current value by option name; returns false if the"
    )
    .unwrap();
    writeln!(
        out,
        "    /// option is unknown or the value is not one of its allowed `values`."
    )
    .unwrap();
    writeln!(
        out,
        "    pub fn set(&mut self, option: &str, value: &str) -> bool {{"
    )
    .unwrap();
    writeln!(
        out,
        "        let Some(st) = lookup_settable(option) else {{ return false; }};"
    )
    .unwrap();
    writeln!(
        out,
        "        if !st.values.split('|').any(|v| v == value) {{ return false; }}"
    )
    .unwrap();
    writeln!(out, "        match option {{").unwrap();
    for r in rows {
        let opt = r.option.as_str();
        writeln!(
            out,
            "            {} => {{ self.{} = value.to_string(); true }}",
            rlit(opt),
            ident(opt)
        )
        .unwrap();
    }
    writeln!(out, "            _ => false,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    writeln!(
        out,
        "    /// Current value for options with a live reader; `None` otherwise."
    )
    .unwrap();
    writeln!(
        out,
        "    pub fn live_value(&self, option: &str) -> Option<&str> {{"
    )
    .unwrap();
    writeln!(out, "        match option {{").unwrap();
    for r in rows {
        let opt = r.option.as_str();
        if opt_live(r).is_none() {
            continue;
        }
        writeln!(
            out,
            "            {} => Some(self.{}.as_str()),",
            rlit(opt),
            ident(opt)
        )
        .unwrap();
    }
    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    writeln!(
        out,
        "    /// Build the live value of a settable from the architecture-side flag,"
    )
    .unwrap();
    writeln!(
        out,
        "    /// reproducing `kunaLiveValue`'s bool / inverted-bool / print mapping."
    )
    .unwrap();
    writeln!(out, "    ///").unwrap();
    writeln!(
        out,
        "    /// `read_flag(field)` returns the architecture bool member named `field`"
    )
    .unwrap();
    writeln!(
        out,
        "    /// (e.g. `present_lessequal`); the special `__print_arraynotation` field"
    )
    .unwrap();
    writeln!(
        out,
        "    /// is the `PrintC::getArrayNotation()` flag. Returns `None` for options"
    )
    .unwrap();
    writeln!(
        out,
        "    /// with no live reader (same set as [`OptionValues::live_value`])."
    )
    .unwrap();
    writeln!(
        out,
        "    pub fn live_from_arch<'a>(option: &str, read_flag: impl Fn(&str) -> Option<bool>) -> Option<&'a str> {{"
    )
    .unwrap();
    writeln!(out, "        match option {{").unwrap();
    for r in rows {
        let opt = r.option.as_str();
        let Some((field, true_val, false_val)) = opt_live(r) else {
            continue;
        };
        writeln!(
            out,
            "            {} => match read_flag({}) {{ Some(true) => Some({}), Some(false) => Some({}), None => None }},",
            rlit(opt),
            rlit(field),
            rlit(true_val),
            rlit(false_val),
        )
        .unwrap();
    }
    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();
}

fn opt_live(r: &Settable) -> Option<(&str, &str, &str)> {
    match (&r.live_field, &r.live_true, &r.live_false) {
        (Some(field), Some(yes), Some(no)) => Some((field, yes, no)),
        (None, None, None) => None,
        _ => panic!("phases.toml: incomplete live mapping for {}", r.option),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shipped_registry_generates_the_compiled_tables() {
        let generated = generate(include_str!("phases.toml")).unwrap();
        assert_eq!(
            generated,
            include_str!(concat!(env!("OUT_DIR"), "/phases_generated.rs"))
        );
    }

    #[test]
    fn live_mappings_are_complete_or_absent() {
        let registry: Registry = toml::from_str(include_str!("phases.toml")).unwrap();
        let mut row = registry.settable.into_iter().next().unwrap();
        for mask in 0..8 {
            row.live_field = (mask & 1 != 0).then(|| "flag".into());
            row.live_true = (mask & 2 != 0).then(|| "on".into());
            row.live_false = (mask & 4 != 0).then(|| "off".into());
            let result = std::panic::catch_unwind(|| opt_live(&row));
            assert_eq!(result.is_ok(), matches!(mask, 0 | 7), "mask {mask}");
        }
    }
}
