//! Codegen for the kuna phase registry (ADR 0006).
//!
//! Reads `phases.toml` (the single source of truth for the four static tables
//! transcribed from `decompiler/cpp/kuna_stages.cc`) and generates
//! `$OUT_DIR/phases_generated.rs`, which `kuna_phases.rs` includes. The
//! generated code is:
//!
//!   - the four static tables: `GROUP_TABLE`, `SUBPHASE_TABLE`,
//!     `SURFACE_TABLE`, `SETTABLE_TABLE` (slices of the structs defined in
//!     `kuna_phases.rs`);
//!   - a typed `OptionValues` struct: one field per settable, holding the
//!     option's allowed-value enum, defaulting to the shipped value;
//!   - `OptionValues::default()` (= the `default` column of `settableTable`);
//!   - the `live_value(field, &OptionValues)` lookup that maps a settable
//!     option name to its live value string (the codegen half of
//!     `kuna_console.cc` `kunaLiveValue`).
//!
//! TOML is parsed by a small hand-rolled reader (the file is generated by us
//! and uses only `[[array-of-table]]` headers + `key = "string"` /
//! `key = true|false` lines), so the build stays dependency-free and offline.
//! That parser is intentionally narrow: it rejects anything outside the shape
//! `phases.toml` actually uses, turning a malformed registry into a build
//! error rather than silently-wrong codegen.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// One parsed `[[table]]` row: ordered key -> value, preserving file order.
type Row = Vec<(String, TomlValue)>;

/// A TOML scalar value as used by `phases.toml`.
#[derive(Clone, Debug)]
enum TomlValue {
    Str(String),
    Bool(bool),
}

impl TomlValue {
    fn as_str(&self) -> &str {
        match self {
            TomlValue::Str(s) => s,
            TomlValue::Bool(_) => panic!("phases.toml: expected string, found bool"),
        }
    }
    fn as_bool(&self) -> bool {
        match self {
            TomlValue::Bool(b) => *b,
            TomlValue::Str(_) => panic!("phases.toml: expected bool, found string"),
        }
    }
}

/// Get a required key from a row.
fn req<'a>(row: &'a Row, key: &str) -> &'a TomlValue {
    row.iter()
        .find(|(k, _)| k == key)
        .map(|(_, v)| v)
        .unwrap_or_else(|| panic!("phases.toml: missing required key `{key}` in a row"))
}

/// Get an optional key from a row.
fn opt<'a>(row: &'a Row, key: &str) -> Option<&'a TomlValue> {
    row.iter().find(|(k, _)| k == key).map(|(_, v)| v)
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let toml_path = Path::new(&manifest_dir).join("phases.toml");
    println!("cargo:rerun-if-changed=phases.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let text = fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", toml_path.display()));
    let tables = parse_toml(&text);

    let groups = tables.get("group").cloned().unwrap_or_default();
    let substages = tables.get("subphase").cloned().unwrap_or_default();
    let surfaces = tables.get("surface").cloned().unwrap_or_default();
    let settables = tables.get("settable").cloned().unwrap_or_default();

    let mut out = String::new();
    out.push_str("// @generated by build.rs from phases.toml -- DO NOT EDIT.\n\n");

    gen_groups(&mut out, &groups);
    gen_subphases(&mut out, &substages);
    gen_surfaces(&mut out, &surfaces);
    gen_settables(&mut out, &settables);
    gen_option_values(&mut out, &settables);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("phases_generated.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

// -----------------------------------------------------------------------------
// Stage / strength enum rendering (the codegen turns "S3" etc. into the variant)
// -----------------------------------------------------------------------------

/// Render a phase code ("P0".."P9" or "infra") as a `KunaPhase` variant path.
fn phase_variant(code: &str) -> String {
    let v = match code {
        "infra" => "Infra",
        "P0" => "P0",
        "P1" => "P1",
        "P2" => "P2",
        "P3" => "P3",
        "P4" => "P4",
        "P5" => "P5",
        "P6" => "P6",
        "P7" => "P7",
        "P8" => "P8",
        "P9" => "P9",
        other => panic!("phases.toml: bad phase code `{other}`"),
    };
    format!("KunaPhase::{v}")
}

/// Render a strength code ("NONE"/"HINT"/"HARD") as a `KunaStrength` variant.
fn strength_variant(code: &str) -> String {
    let v = match code {
        "NONE" => "None",
        "HINT" => "Hint",
        "HARD" => "Hard",
        other => panic!("phases.toml: bad strength code `{other}`"),
    };
    format!("KunaStrength::{v}")
}

/// Escape a string for a Rust string literal.
fn rlit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

// -----------------------------------------------------------------------------
// Table codegen
// -----------------------------------------------------------------------------

fn gen_groups(out: &mut String, rows: &[Row]) {
    writeln!(
        out,
        "/// groupTable: every action/rule group name -> its dominant phase."
    )
    .unwrap();
    writeln!(
        out,
        "pub static GROUP_TABLE: [KunaGroupEntry; {}] = [",
        rows.len()
    )
    .unwrap();
    for r in rows {
        writeln!(
            out,
            "    KunaGroupEntry {{ group: {}, phase: {}, subphase: {}, note: {} }},",
            rlit(req(r, "group").as_str()),
            phase_variant(req(r, "phase").as_str()),
            rlit(req(r, "subphase").as_str()),
            rlit(req(r, "note").as_str()),
        )
        .unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

fn gen_subphases(out: &mut String, rows: &[Row]) {
    writeln!(out, "/// subphaseTable: every named decision point.").unwrap();
    writeln!(
        out,
        "pub static SUBPHASE_TABLE: [KunaSubPhase; {}] = [",
        rows.len()
    )
    .unwrap();
    for r in rows {
        writeln!(
            out,
            "    KunaSubPhase {{ name: {}, phase: {}, decision: {}, assertion: {}, strength: {}, rewind: {}, latent: {}, exposure: {} }},",
            rlit(req(r, "name").as_str()),
            phase_variant(req(r, "phase").as_str()),
            rlit(req(r, "decision").as_str()),
            rlit(req(r, "assertion").as_str()),
            strength_variant(req(r, "strength").as_str()),
            phase_variant(req(r, "rewind").as_str()),
            req(r, "latent").as_bool(),
            rlit(req(r, "exposure").as_str()),
        )
        .unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

fn gen_surfaces(out: &mut String, rows: &[Row]) {
    writeln!(
        out,
        "/// surfaceTable: existing console/option surface -> the sub-phase it operates."
    )
    .unwrap();
    writeln!(
        out,
        "pub static SURFACE_TABLE: [KunaSurfaceEntry; {}] = [",
        rows.len()
    )
    .unwrap();
    for r in rows {
        writeln!(
            out,
            "    KunaSurfaceEntry {{ surface: {}, phase: {}, subphase: {}, note: {} }},",
            rlit(req(r, "surface").as_str()),
            phase_variant(req(r, "phase").as_str()),
            rlit(req(r, "subphase").as_str()),
            rlit(req(r, "note").as_str()),
        )
        .unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

fn gen_settables(out: &mut String, rows: &[Row]) {
    writeln!(
        out,
        "/// settableTable: one row per kuna ArchOption -- the LLM control surface."
    )
    .unwrap();
    writeln!(
        out,
        "pub static SETTABLE_TABLE: [KunaSettable; {}] = [",
        rows.len()
    )
    .unwrap();
    for r in rows {
        writeln!(out, "    KunaSettable {{").unwrap();
        writeln!(out, "        option: {},", rlit(req(r, "option").as_str())).unwrap();
        writeln!(out, "        values: {},", rlit(req(r, "values").as_str())).unwrap();
        writeln!(out, "        shipped: {},", rlit(req(r, "default").as_str())).unwrap();
        writeln!(out, "        destructive: {},", req(r, "destructive").as_bool()).unwrap();
        writeln!(out, "        phase: {},", phase_variant(req(r, "phase").as_str())).unwrap();
        writeln!(out, "        subphase: {},", rlit(req(r, "subphase").as_str())).unwrap();
        writeln!(
            out,
            "        strength: {},",
            strength_variant(req(r, "strength").as_str())
        )
        .unwrap();
        writeln!(out, "        rewind: {},", phase_variant(req(r, "rewind").as_str())).unwrap();
        writeln!(out, "        issue: {},", rlit(req(r, "issue").as_str())).unwrap();
        writeln!(out, "        summary: {},", rlit(req(r, "summary").as_str())).unwrap();
        writeln!(out, "        use_when: {},", rlit(req(r, "use_when").as_str())).unwrap();
        writeln!(out, "        example: {},", rlit(req(r, "example").as_str())).unwrap();
        writeln!(
            out,
            "        source_decompiler: {},",
            rlit(req(r, "source_decompiler").as_str())
        )
        .unwrap();
        writeln!(out, "        inspiration: {},", rlit(req(r, "inspiration").as_str())).unwrap();
        writeln!(out, "        change_kind: {},", rlit(req(r, "change_kind").as_str())).unwrap();
        let tier = req(r, "tier").as_str();
        match tier {
            "core" | "transform" | "analysis" => {}
            other => panic!("phases.toml: bad tier `{other}` (need core|transform|analysis)"),
        }
        writeln!(out, "        tier: {},", rlit(tier)).unwrap();
        writeln!(out, "        symptoms: {},", rlit(req(r, "symptoms").as_str())).unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

// -----------------------------------------------------------------------------
// Typed OptionValues + live-value codegen (kuna_console.cc kunaLiveValue)
// -----------------------------------------------------------------------------

/// Turn an option name into a valid Rust field/ident (kebab/option names are
/// already lower_snake-safe here, but normalize defensively).
fn ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// Generate the typed `OptionValues` struct + its `Default` + `set`/`get` +
/// `live_value` lookup, mirroring `kunaLiveValue`'s string mapping.
///
/// Each settable becomes a `String` field holding the option's *current* value
/// (one of its pipe-separated `values`), initialized to the shipped `default`.
/// `live_value(option) -> Option<&str>` reproduces `kunaLiveValue`: it returns
/// the live string for the 19 options that have a reader, and `None`
/// (i.e. C++ `""`) for the rest -- so the catalog emitter suppresses the
/// `current` field for exactly the same options as the C++ does.
fn gen_option_values(out: &mut String, rows: &[Row]) {
    writeln!(
        out,
        "/// Typed live option values (ADR 0006): one field per settable, holding the"
    )
    .unwrap();
    writeln!(
        out,
        "/// option's *current* value (one of its allowed `values`); defaults to the"
    )
    .unwrap();
    writeln!(
        out,
        "/// shipped `default`. `live_value` reproduces `kuna_console.cc kunaLiveValue`."
    )
    .unwrap();
    writeln!(out, "#[derive(Clone, Debug, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub struct OptionValues {{").unwrap();
    for r in rows {
        let opt = req(r, "option").as_str();
        writeln!(
            out,
            "    /// Current value of `{}` (allowed: {}).",
            opt,
            req(r, "values").as_str()
        )
        .unwrap();
        writeln!(out, "    pub {}: String,", ident(opt)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();

    // Default
    writeln!(out, "impl Default for OptionValues {{").unwrap();
    writeln!(out, "    fn default() -> Self {{").unwrap();
    writeln!(out, "        OptionValues {{").unwrap();
    for r in rows {
        let opt = req(r, "option").as_str();
        let def = req(r, "default").as_str();
        writeln!(
            out,
            "            {}: {}.to_string(),",
            ident(opt),
            rlit(def)
        )
        .unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();

    // get / set by option name
    writeln!(out, "impl OptionValues {{").unwrap();
    writeln!(
        out,
        "    /// Get a settable's current value by option name (None if unknown)."
    )
    .unwrap();
    writeln!(out, "    pub fn get(&self, option: &str) -> Option<&str> {{").unwrap();
    writeln!(out, "        match option {{").unwrap();
    for r in rows {
        let opt = req(r, "option").as_str();
        writeln!(
            out,
            "            {} => Some(self.{}.as_str()),",
            rlit(opt),
            ident(opt)
        )
        .unwrap();
    }
    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    writeln!(
        out,
        "    /// Set a settable's current value by option name; returns false if the"
    )
    .unwrap();
    writeln!(
        out,
        "    /// option is unknown or the value is not one of its allowed `values`."
    )
    .unwrap();
    writeln!(
        out,
        "    pub fn set(&mut self, option: &str, value: &str) -> bool {{"
    )
    .unwrap();
    writeln!(
        out,
        "        let Some(st) = lookup_settable(option) else {{ return false; }};"
    )
    .unwrap();
    writeln!(
        out,
        "        if !st.values.split('|').any(|v| v == value) {{ return false; }}"
    )
    .unwrap();
    writeln!(out, "        match option {{").unwrap();
    for r in rows {
        let opt = req(r, "option").as_str();
        writeln!(
            out,
            "            {} => {{ self.{} = value.to_string(); true }}",
            rlit(opt),
            ident(opt)
        )
        .unwrap();
    }
    writeln!(out, "            _ => false,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    // live_value: codegen of kunaLiveValue. Driven by the live_* keys in TOML.
    writeln!(
        out,
        "    /// The live value of a settable (codegen of `kuna_console.cc kunaLiveValue`)."
    )
    .unwrap();
    writeln!(
        out,
        "    ///"
    )
    .unwrap();
    writeln!(
        out,
        "    /// Returns `None` (C++ `\"\"`) for the three options with no live reader"
    )
    .unwrap();
    writeln!(
        out,
        "    /// (loweredswitch/stackguard/namestyle), so the catalog emitter suppresses"
    )
    .unwrap();
    writeln!(
        out,
        "    /// the `current` field for exactly the same options as the C++ does."
    )
    .unwrap();
    writeln!(
        out,
        "    pub fn live_value(&self, option: &str) -> Option<&str> {{"
    )
    .unwrap();
    writeln!(out, "        match option {{").unwrap();
    for r in rows {
        let opt = req(r, "option").as_str();
        if opt_live(r).is_none() {
            continue;
        }
        // The live value IS the stored current value (the OptionValues field
        // holds the live string directly, in the option's own value vocabulary).
        writeln!(
            out,
            "            {} => Some(self.{}.as_str()),",
            rlit(opt),
            ident(opt)
        )
        .unwrap();
    }
    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    // live_from_arch: maps an Architecture's bool/print flags to the live string,
    // reproducing kunaLiveValue's bool/bool_inv/print kinds. The caller passes a
    // closure that reads the named arch field as a bool (the W4 architecture
    // wiring); this keeps the codegen the single owner of the option<->field map.
    writeln!(
        out,
        "    /// Build the live value of a settable from the architecture-side flag,"
    )
    .unwrap();
    writeln!(
        out,
        "    /// reproducing `kunaLiveValue`'s bool / inverted-bool / print mapping."
    )
    .unwrap();
    writeln!(
        out,
        "    ///"
    )
    .unwrap();
    writeln!(
        out,
        "    /// `read_flag(field)` returns the architecture bool member named `field`"
    )
    .unwrap();
    writeln!(
        out,
        "    /// (e.g. `present_lessequal`); the special `__print_arraynotation` field"
    )
    .unwrap();
    writeln!(
        out,
        "    /// is the `PrintC::getArrayNotation()` flag. Returns `None` for options"
    )
    .unwrap();
    writeln!(
        out,
        "    /// with no live reader (same set as [`OptionValues::live_value`])."
    )
    .unwrap();
    writeln!(
        out,
        "    pub fn live_from_arch<'a>(option: &str, read_flag: impl Fn(&str) -> Option<bool>) -> Option<&'a str> {{"
    )
    .unwrap();
    writeln!(out, "        match option {{").unwrap();
    for r in rows {
        let opt = req(r, "option").as_str();
        let Some((field, true_val, false_val)) = opt_live(r) else {
            continue;
        };
        // C++ kunaLiveValue is a literal `flag ? live_true : live_false` ternary
        // per option (e.g. compareform = present_lessequal ? "original":"canonical");
        // live_true/live_false are stored verbatim, no inversion logic.
        writeln!(
            out,
            "            {} => match read_flag({}) {{ Some(true) => Some({}), Some(false) => Some({}), None => None }},",
            rlit(opt),
            rlit(&field),
            rlit(&true_val),
            rlit(&false_val),
        )
        .unwrap();
    }
    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();
}

/// Extract the live mapping (field, value-when-true, value-when-false) from a
/// settable row, if it has a live reader. `live_true`/`live_false` are the
/// literal C++ `kunaLiveValue` ternary branches for the option.
fn opt_live(r: &Row) -> Option<(String, String, String)> {
    let field = opt(r, "live_field")?.as_str().to_string();
    let live_true = req(r, "live_true").as_str().to_string();
    let live_false = req(r, "live_false").as_str().to_string();
    Some((field, live_true, live_false))
}

// -----------------------------------------------------------------------------
// Minimal TOML reader (only the `[[table]]` + `key = "str"|bool` shape we emit)
// -----------------------------------------------------------------------------

/// Parse the (self-generated) `phases.toml` into `table-name -> rows`.
///
/// Supports exactly: blank lines, `#` comments, `[[name]]` array-of-table
/// headers, and `key = value` where `value` is a TOML basic string (`"..."`
/// with `\"`, `\\`, `\n`, `\t`, `\r`, `\uXXXX` escapes) or a bare `true`/`false`.
/// Anything else is a hard error (we control the file's shape).
fn parse_toml(text: &str) -> BTreeMap<String, Vec<Row>> {
    let mut tables: BTreeMap<String, Vec<Row>> = BTreeMap::new();
    let mut cur_table: Option<String> = None;

    for (lineno, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(rest) = line.strip_prefix("[[") {
            let name = rest
                .strip_suffix("]]")
                .unwrap_or_else(|| panic!("phases.toml:{}: bad table header `{line}`", lineno + 1))
                .trim()
                .to_string();
            tables.entry(name.clone()).or_default().push(Row::new());
            cur_table = Some(name);
            continue;
        }
        // key = value
        let eq = line
            .find('=')
            .unwrap_or_else(|| panic!("phases.toml:{}: expected `key = value`, got `{line}`", lineno + 1));
        let key = line[..eq].trim().to_string();
        let valstr = line[eq + 1..].trim();
        let value = parse_value(valstr, lineno + 1);
        let table = cur_table
            .as_ref()
            .unwrap_or_else(|| panic!("phases.toml:{}: key `{key}` outside any [[table]]", lineno + 1));
        tables
            .get_mut(table)
            .expect("table present")
            .last_mut()
            .expect("at least one row")
            .push((key, value));
    }
    tables
}

/// Parse a single TOML scalar value (basic string or bool).
fn parse_value(s: &str, lineno: usize) -> TomlValue {
    if s == "true" {
        return TomlValue::Bool(true);
    }
    if s == "false" {
        return TomlValue::Bool(false);
    }
    let bytes = s.as_bytes();
    if bytes.first() != Some(&b'"') || bytes.last() != Some(&b'"') || s.len() < 2 {
        panic!("phases.toml:{lineno}: unsupported value `{s}` (need a basic string or bool)");
    }
    let inner = &s[1..s.len() - 1];
    let mut out = String::with_capacity(inner.len());
    let mut chars = inner.chars();
    while let Some(c) = chars.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        match chars.next() {
            Some('"') => out.push('"'),
            Some('\\') => out.push('\\'),
            Some('n') => out.push('\n'),
            Some('t') => out.push('\t'),
            Some('r') => out.push('\r'),
            Some('u') => {
                let hex: String = (0..4).filter_map(|_| chars.next()).collect();
                let code = u32::from_str_radix(&hex, 16)
                    .unwrap_or_else(|_| panic!("phases.toml:{lineno}: bad \\u escape"));
                out.push(char::from_u32(code).unwrap_or('\u{fffd}'));
            }
            other => panic!("phases.toml:{lineno}: bad escape `\\{other:?}`"),
        }
    }
    TomlValue::Str(out)
}
