#!/usr/bin/env bash
# Open (or stage) a PR for the current feature branch, robustly.
#
#   tools/pipeline/open_pr.sh <branch> <title> <body-file> [<record.json>]
#
# Pushes <branch> over SSH (always works here), then tries `gh pr create`. If gh cannot
# create the PR (e.g. the gh token lacks access to the org repo, while the SSH key can
# push), it falls back to printing a ready-to-click compare URL. Emits the resulting URL
# on the LAST stdout line (PR URL or compare URL) so the caller can record it.
#
# If <record.json> is given, a REAL captured before/after demonstration (kuna with the
# feature off vs on, on the function the feature was built for, plus the reference
# rendering) is generated by `kuna.pipeline.prdemo` and appended to the PR's opening
# comment -- so every PR shows what the feature does on a relevant target.
set -uo pipefail

BRANCH="${1:?need branch}"
TITLE="${2:?need title}"
BODY_FILE="${3:?need body file}"
RECORD="${4:-}"
REPO_SLUG="${PIPELINE_REPO:-Noelo-Lab/kuna}"
BASE="${BASE_BRANCH:-main}"
KUNA_PY="${KUNA_PY:-$HOME/.virtualenvs/kuna/bin/python}"

# 0. build the final body: the worker's pr_body + a generated before/after demo
FINAL_BODY="$BODY_FILE"
if [ -n "$RECORD" ] && [ -f "$RECORD" ]; then
  DEMO="$(mktemp)"
  if "$KUNA_PY" -m kuna.pipeline.prdemo --record "$RECORD" > "$DEMO" 2>/dev/null && [ -s "$DEMO" ]; then
    FINAL_BODY="$(mktemp)"
    cat "$BODY_FILE" > "$FINAL_BODY"
    printf '\n\n---\n\n' >> "$FINAL_BODY"
    cat "$DEMO" >> "$FINAL_BODY"
    echo "embedded before/after demo from $RECORD" 1>&2
  else
    echo "WARN: prdemo failed; PR body has no generated demo" 1>&2
  fi
fi

# 1. push the branch (SSH; pre-authorized)
git push origin "HEAD:refs/heads/$BRANCH" 1>&2 || { echo "ERROR: push failed" 1>&2; exit 1; }

# 2. create the PR via the REST API (gh api). NOTE: `gh pr create`/`gh pr edit` use a
# GraphQL path that fetches projectCards; GitHub's classic-Projects sunset now rejects that
# for this repo, so those commands fail. The REST API avoids it entirely.
if command -v gh >/dev/null 2>&1; then
  OWNER="${REPO_SLUG%%/*}"
  URL="$(gh api -X POST "repos/$REPO_SLUG/pulls" \
           -f title="$TITLE" -f head="$BRANCH" -f base="$BASE" -F body=@"$FINAL_BODY" \
           -q .html_url 2>/tmp/_ghpr.err)" && {
    echo "opened PR: $URL" 1>&2
    echo "$URL"
    exit 0
  }
  # already-exists (422) -> find the open PR for this branch and update its body (idempotent)
  NUM="$(gh api "repos/$REPO_SLUG/pulls?head=$OWNER:$BRANCH&state=open" -q '.[0].number' 2>/dev/null)"
  if [ -n "$NUM" ] && [ "$NUM" != "null" ]; then
    URL="$(gh api -X PATCH "repos/$REPO_SLUG/pulls/$NUM" -F body=@"$FINAL_BODY" -q .html_url 2>/dev/null)"
    echo "PR #$NUM already open; refreshed body: $URL" 1>&2
    echo "$URL"
    exit 0
  fi
  echo "gh api pulls failed: $(cat /tmp/_ghpr.err 2>/dev/null | head -2)" 1>&2
fi

# 3. fallback: compare URL the human can click to open the PR
CMP="https://github.com/$REPO_SLUG/compare/$BASE...$BRANCH?expand=1"
echo "PR not auto-created (gh token lacks repo access). Branch pushed; open via:" 1>&2
echo "  $CMP" 1>&2
echo "$CMP"
exit 0
