//! Port of `decompiler/cpp/kuna_stages.{cc,hh}` — the kuna stage registry.
//!
//! This is the normative stage model made physical: pure static data + lookups
//! (no pipeline linkage, no output effect). It encodes
//!
//!   - the stages themselves ([`KunaStage`]): the P0 knowledge plane + S1..S9,
//!     with Band B (S3..S6) membership, plus the `Infra` registry-only
//!     pseudo-stage for orchestration units;
//!   - the four static tables transcribed from `kuna_stages.cc`:
//!     [`GROUP_TABLE`] (39 action/rule groups), [`SUBSTAGE_TABLE`] (40 named
//!     decision points), [`SURFACE_TABLE`] (90 console/option surfaces), and
//!     [`SETTABLE_TABLE`] (22 LLM/agent-settable assertions);
//!   - the lookup API (`kuna_num_groups`/`kuna_group_by_index`/`lookup_group`
//!     and siblings — the idiomatic equivalents of the C++ `kunaNumGroups` /
//!     `kunaGroupByIndex` / `kunaLookupGroup` family).
//!
//! Per ADR 0006 the four tables and the typed [`OptionValues`] struct are
//! **generated by `build.rs` from `stages.toml`** (the single source of truth):
//! the generated code is `include!`d below. The catalog JSON emitter
//! ([`emit_settable_json`]) is hand-written to be byte-compatible with
//! `kuna_console.cc kunaEmitSettableJson` (ADR 0006); `tests/catalog_bytecompat.rs`
//! string-matches it against the C++ binary's captured output.

use core::fmt;

/// (kuna) The stages of the kuna stage model (`docs/stages.md`).
///
/// `Infra` is the registry-only pseudo-stage for orchestration units
/// (ActionStart/Stop, the cleanup pool's termination policy) that own no model
/// artifact — the C++ `kstage_infra = -1`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum KunaStage {
    /// Orchestration / termination policy (no artifact) — C++ `kstage_infra`.
    Infra,
    /// Knowledge & Configuration Plane (orthogonal) — C++ `kstage_p0`.
    P0,
    /// Image & Code Partition — C++ `kstage_s1`.
    S1,
    /// Flow & Op-Graph Recovery — C++ `kstage_s2`.
    S2,
    /// Definition Web (Band B) — C++ `kstage_s3`.
    S3,
    /// Call & Prototype Model (Band B) — C++ `kstage_s4`.
    S4,
    /// Value & Type Facts (Band B) — C++ `kstage_s5`.
    S5,
    /// Variable & Storage Model (Band B) — C++ `kstage_s6`.
    S6,
    /// Region Hierarchy — C++ `kstage_s7`.
    S7,
    /// Structured AST & Goto Quality — C++ `kstage_s8`.
    S8,
    /// Surface Rendering & Refinement — C++ `kstage_s9`.
    S9,
}

impl KunaStage {
    /// The numeric value of the stage matching the C++ `enum KunaStage` (infra
    /// is -1, P0 is 0, S1..S9 are 1..9).
    pub fn index(self) -> i32 {
        match self {
            KunaStage::Infra => -1,
            KunaStage::P0 => 0,
            KunaStage::S1 => 1,
            KunaStage::S2 => 2,
            KunaStage::S3 => 3,
            KunaStage::S4 => 4,
            KunaStage::S5 => 5,
            KunaStage::S6 => 6,
            KunaStage::S7 => 7,
            KunaStage::S8 => 8,
            KunaStage::S9 => 9,
        }
    }

    /// "P0".."S9" (or "--" for infra) — C++ `kunaStageCode`.
    pub fn code(self) -> &'static str {
        STAGE_CODES[self.code_index()]
    }

    /// Long stage name — C++ `kunaStageName`.
    pub fn name(self) -> &'static str {
        STAGE_NAMES[self.code_index()]
    }

    /// The artifact the stage owns — C++ `kunaStageArtifact`.
    pub fn artifact(self) -> &'static str {
        STAGE_ARTIFACTS[self.code_index()]
    }

    /// true for S3..S6 — C++ `kunaStageInBandB`.
    pub fn in_band_b(self) -> bool {
        // C++: (stage >= kstage_s3 && stage <= kstage_s6); the enum ordering of
        // S3..S6 mirrors the numeric one (infra=-1 sorts below P0).
        let i = self.index();
        (KunaStage::S3.index()..=KunaStage::S6.index()).contains(&i)
    }

    /// Index into the `STAGE_*` arrays: 0..=9 for P0..S9, 10 for infra.
    fn code_index(self) -> usize {
        match self {
            KunaStage::Infra => 10,
            other => other.index() as usize,
        }
    }

    /// Parse "P0"/"s3"/... into the stage — C++ `kunaStageFromCode`.
    ///
    /// Returns `None` on a malformed code (the C++ returns `false` and leaves
    /// `res` unset).
    pub fn from_code(code: &str) -> Option<KunaStage> {
        if code.len() != 2 {
            return None;
        }
        let bytes = code.as_bytes();
        let c0 = bytes[0];
        let c1 = bytes[1];
        if (c0 == b'p' || c0 == b'P') && c1 == b'0' {
            return Some(KunaStage::P0);
        }
        if (c0 == b's' || c0 == b'S') && (b'1'..=b'9').contains(&c1) {
            // C++: res = (KunaStage)(c1 - '0'); S1..S9 are 1..9.
            return Some(match c1 - b'0' {
                1 => KunaStage::S1,
                2 => KunaStage::S2,
                3 => KunaStage::S3,
                4 => KunaStage::S4,
                5 => KunaStage::S5,
                6 => KunaStage::S6,
                7 => KunaStage::S7,
                8 => KunaStage::S8,
                9 => KunaStage::S9,
                _ => unreachable!("c1 guaranteed in 1..=9"),
            });
        }
        None
    }
}

/// (kuna) Assertion strength (`stage-model.md` section 2) — C++ `KunaStrength`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum KunaStrength {
    /// No assertion exists (fully LATENT decision) — C++ `kstrength_none`.
    None,
    /// Biases inference — C++ `kstrength_hint`.
    Hint,
    /// Blocks inference unconditionally — C++ `kstrength_hard`.
    Hard,
}

impl KunaStrength {
    /// "HARD"/"HINT"/"NONE" — the catalog rendering of a strength.
    pub fn catalog_code(self) -> &'static str {
        match self {
            KunaStrength::Hard => "HARD",
            KunaStrength::Hint => "HINT",
            KunaStrength::None => "NONE",
        }
    }
}

/// (kuna) One action/rule group mapped to its dominant stage — C++ `KunaGroupEntry`.
#[derive(Clone, Copy, Debug)]
pub struct KunaGroupEntry {
    /// Group name as used in `coreaction.cc`.
    pub group: &'static str,
    /// Dominant stage (straddlers: by owned artifact, section 15).
    pub stage: KunaStage,
    /// Sub-stage operated, or "" if stage-wide.
    pub substage: &'static str,
    /// Straddler / secondary-effect note, or "".
    pub note: &'static str,
}

/// (kuna) One sub-stage: a named decision point inside a stage — C++ `KunaSubStage`.
#[derive(Clone, Copy, Debug)]
pub struct KunaSubStage {
    /// Short kebab-case name (stable identifier).
    pub name: &'static str,
    /// Owning stage.
    pub stage: KunaStage,
    /// What is being decided.
    pub decision: &'static str,
    /// The P0 assertion type that overrides it.
    pub assertion: &'static str,
    /// Strength of that assertion.
    pub strength: KunaStrength,
    /// Minimal invalidated stage (section 12); Ghidra-actual is whole-function.
    pub rewind: KunaStage,
    /// true = no override surface exists in kuna today.
    pub latent: bool,
    /// Surface that operates it ("option ...", "command ...", or roadmap note).
    pub exposure: &'static str,
}

/// (kuna) One existing console/option surface routed to a sub-stage — C++ `KunaSurfaceEntry`.
#[derive(Clone, Copy, Debug)]
pub struct KunaSurfaceEntry {
    /// "option <name>" or the console command words.
    pub surface: &'static str,
    /// Stage it operates.
    pub stage: KunaStage,
    /// Sub-stage name (in the catalog), or "".
    pub substage: &'static str,
    /// Clarification, or "".
    pub note: &'static str,
}

/// (kuna) One LLM/agent-settable assertion: the machine-readable catalog row —
/// C++ `KunaSettable`.
#[derive(Clone, Copy, Debug)]
pub struct KunaSettable {
    /// The option name (the `option <name> ...` token).
    pub option: &'static str,
    /// Pipe-separated legal values, e.g. "on|off" or "canonical|original".
    pub values: &'static str,
    /// The value kuna ships as the default (post-DIV-2 where applicable).
    pub shipped: &'static str,
    /// true = NOT safe as a global default (kept opt-in).
    pub destructive: bool,
    /// Owning stage.
    pub stage: KunaStage,
    /// Sub-stage name (in the §4-§10 catalog).
    pub substage: &'static str,
    /// Assertion strength.
    pub strength: KunaStrength,
    /// Minimal invalidated stage (REPORTED; Ghidra-actual is whole-function).
    pub rewind: KunaStage,
    /// Originating issue (e.g. "GH-558"), or "".
    pub issue: &'static str,
    /// One line: the decision this assertion controls.
    pub summary: &'static str,
    /// Symptom -> when an operator should flip it away from the default.
    pub use_when: &'static str,
    /// A ready-to-use console command, e.g. "option compareform canonical".
    pub example: &'static str,
    /// (kuna) Which decompiler the behavior was observed/ported from.
    pub source_decompiler: &'static str,
    /// (kuna) Concrete origin pointer (upstream issue/PR, or reference class).
    pub inspiration: &'static str,
    /// (kuna) Gates default-on eligibility.
    pub change_kind: &'static str,
}

// --- The STAGE_* string tables (C++ kuna_stages.cc:16-43) --------------------

/// "P0".."S9","--" — index 10 is infra (C++ `STAGE_CODES`).
static STAGE_CODES: [&str; 11] = [
    "P0", "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "--",
];

/// Long stage names — index 10 is infra (C++ `STAGE_NAMES`).
static STAGE_NAMES: [&str; 11] = [
    "Knowledge & Configuration Plane",
    "Image & Code Partition",
    "Flow & Op-Graph Recovery",
    "Definition Web",
    "Call & Prototype Model",
    "Value & Type Facts",
    "Variable & Storage Model",
    "Region Hierarchy",
    "Structured AST & Goto Quality",
    "Surface Rendering & Refinement",
    "Infrastructure / orchestration",
];

/// The artifact each stage owns — index 10 is infra (C++ `STAGE_ARTIFACTS`).
static STAGE_ARTIFACTS: [&str; 11] = [
    "assertion store (Symbol DB + Override) + pipeline configuration",
    "bytes + segments + symbol/data map + code-vs-data partition",
    "lifted ops + CFG (bblocks) + jump tables (jumpvec) + work queues",
    "SSA-as-property over the op-graph; heritage state; dead-definition gate",
    "call specs / prototypes / calling conventions",
    "ranges, consume bits, type lattice",
    "HighVariables, stack-frame layout, alias sets",
    "region tree (sblocks - physically distinct from the CFG)",
    "statement tree + goto set (the quality signal)",
    "text + position maps",
    "(none - schedule/termination policy only)",
];

// --- The four generated tables + the typed OptionValues (ADR 0006) -----------
// build.rs reads stages.toml and emits GROUP_TABLE/SUBSTAGE_TABLE/
// SURFACE_TABLE/SETTABLE_TABLE plus OptionValues. See build.rs.
include!(concat!(env!("OUT_DIR"), "/stages_generated.rs"));

// --- Lookup API (C++ kunaNum*/kuna*ByIndex/kunaLookup*) ----------------------

/// Number of group entries — C++ `kunaNumGroups`.
pub fn kuna_num_groups() -> usize {
    GROUP_TABLE.len()
}

/// Get the i-th group entry — C++ `kunaGroupByIndex`.
pub fn kuna_group_by_index(i: usize) -> &'static KunaGroupEntry {
    &GROUP_TABLE[i]
}

/// Find a group by name (None if missing) — C++ `kunaLookupGroup`.
pub fn lookup_group(nm: &str) -> Option<&'static KunaGroupEntry> {
    GROUP_TABLE.iter().find(|e| e.group == nm)
}

/// Number of catalog sub-stages — C++ `kunaNumSubStages`.
pub fn kuna_num_substages() -> usize {
    SUBSTAGE_TABLE.len()
}

/// Get the i-th sub-stage — C++ `kunaSubStageByIndex`.
pub fn kuna_substage_by_index(i: usize) -> &'static KunaSubStage {
    &SUBSTAGE_TABLE[i]
}

/// Find a sub-stage by name (None if missing) — C++ `kunaLookupSubStage`.
pub fn lookup_substage(nm: &str) -> Option<&'static KunaSubStage> {
    SUBSTAGE_TABLE.iter().find(|e| e.name == nm)
}

/// Number of surface routings — C++ `kunaNumSurfaces`.
pub fn kuna_num_surfaces() -> usize {
    SURFACE_TABLE.len()
}

/// Get the i-th surface routing — C++ `kunaSurfaceByIndex`.
pub fn kuna_surface_by_index(i: usize) -> &'static KunaSurfaceEntry {
    &SURFACE_TABLE[i]
}

/// Find a surface by exact string (None if missing) — C++ `kunaLookupSurface`.
pub fn lookup_surface(nm: &str) -> Option<&'static KunaSurfaceEntry> {
    SURFACE_TABLE.iter().find(|e| e.surface == nm)
}

/// Number of LLM-settable assertions in the catalog — C++ `kunaNumSettables`.
pub fn kuna_num_settables() -> usize {
    SETTABLE_TABLE.len()
}

/// Get the i-th settable assertion — C++ `kunaSettableByIndex`.
pub fn kuna_settable_by_index(i: usize) -> &'static KunaSettable {
    &SETTABLE_TABLE[i]
}

/// Find a settable by option name (None if missing) — C++ `kunaLookupSettable`.
pub fn lookup_settable(nm: &str) -> Option<&'static KunaSettable> {
    SETTABLE_TABLE.iter().find(|e| e.option == nm)
}

// --- The catalog JSON emitter (byte-compatible with kunaEmitSettableJson) ----

/// Append `str` to `out` as a JSON string literal — byte-for-byte port of
/// `kuna_console.cc kunaJsonString` (quotes + minimal escaping; control chars
/// below 0x20 other than `\n` collapse to a single space).
fn json_string(out: &mut String, s: &str) {
    out.push('"');
    for ch in s.chars() {
        if ch == '"' || ch == '\\' {
            out.push('\\');
            out.push(ch);
        } else if ch == '\n' {
            out.push_str("\\n");
        } else if (ch as u32) < 0x20 {
            // C++ drops other control chars to a single space.
            out.push(' ');
        } else {
            out.push(ch);
        }
    }
    out.push('"');
}

/// Emit one settable as a JSON object onto `out` — byte-for-byte port of
/// `kuna_console.cc kunaEmitSettableJson`.
///
/// `live` is the live current value (C++ joins it from the `Architecture`);
/// pass `None` to suppress the `current` field, exactly as the C++ does when
/// `kunaLiveValue` returns `""` (no program loaded, or no live reader).
pub fn emit_settable_json(out: &mut String, st: &KunaSettable, live: Option<&str>) {
    out.push_str("  {");
    out.push_str("\"option\": ");
    json_string(out, st.option);
    out.push_str(", \"values\": [");
    // Split the pipe-separated values into a JSON array. The C++ walks
    // `pos <= vals.size()` so a trailing empty token (vals ending in '|') would
    // emit an empty "" — replicate that with the inclusive loop below; the
    // catalog never ends a values string in '|', so this matches in practice.
    let vals = st.values;
    let mut first = true;
    let mut pos = 0usize;
    loop {
        let rest = &vals[pos..];
        let (tok, next) = match rest.find('|') {
            Some(bar) => (&rest[..bar], Some(pos + bar + 1)),
            None => (rest, None),
        };
        if !first {
            out.push_str(", ");
        }
        json_string(out, tok);
        first = false;
        match next {
            Some(p) => pos = p,
            None => break,
        }
    }
    out.push(']');
    out.push_str(", \"default\": ");
    json_string(out, st.shipped);
    if let Some(live) = live {
        if !live.is_empty() {
            out.push_str(", \"current\": ");
            json_string(out, live);
        }
    }
    out.push_str(", \"destructive_as_default\": ");
    out.push_str(if st.destructive { "true" } else { "false" });
    out.push_str(", \"stage\": ");
    json_string(out, st.stage.code());
    out.push_str(", \"substage\": ");
    json_string(out, st.substage);
    out.push_str(", \"strength\": ");
    json_string(out, st.strength.catalog_code());
    out.push_str(", \"rewind\": ");
    json_string(out, st.rewind.code());
    out.push_str(", \"issue\": ");
    json_string(out, st.issue);
    out.push_str(", \"summary\": ");
    json_string(out, st.summary);
    out.push_str(", \"use_when\": ");
    json_string(out, st.use_when);
    out.push_str(", \"example\": ");
    json_string(out, st.example);
    out.push_str(", \"source_decompiler\": ");
    json_string(out, st.source_decompiler);
    out.push_str(", \"inspiration\": ");
    json_string(out, st.inspiration);
    out.push_str(", \"change_kind\": ");
    json_string(out, st.change_kind);
    out.push('}');
}

/// Emit the full settable catalog as JSON — byte-for-byte port of
/// `IfcKunaStageCatalog::execute`'s no-argument form (`stage catalog`).
///
/// `live` maps an option name to its live current value (or `None`); pass a
/// closure returning `None` for every option to get the static catalog (the
/// no-program-loaded form, which is what `tests/catalog_bytecompat.rs` pins).
/// The output is the exact bytes the console writes (including the trailing
/// newline after each row and the final `]\n`).
pub fn emit_catalog_json(live: impl Fn(&str) -> Option<&'static str>) -> String {
    let mut out = String::new();
    out.push_str("[\n");
    let n = kuna_num_settables();
    for i in 0..n {
        let st = kuna_settable_by_index(i);
        emit_settable_json(&mut out, st, live(st.option));
        if i + 1 < n {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str("]\n");
    out
}

/// Emit a single settable's catalog JSON — byte-for-byte port of
/// `IfcKunaStageCatalog::execute`'s one-argument form (`stage catalog <option>`).
///
/// Returns `None` if the option is unknown (the C++ throws an
/// `IfaceExecutionError`); the row is followed by a single newline.
pub fn emit_catalog_json_one(option: &str, live: Option<&str>) -> Option<String> {
    let st = lookup_settable(option)?;
    let mut out = String::new();
    emit_settable_json(&mut out, st, live);
    out.push('\n');
    Some(out)
}

impl fmt::Display for KunaStage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.code())
    }
}

#[cfg(test)]
mod tests;
